<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_hispmd_indicators_data  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		if ($data["Data Source"] == "IR Assessment") { 
    if ($data["Value"] >= 95) {
        $record["value_style"] = 'style="background:green;"';
    } elseif ($data["value"] >= 80) {
        $record["value_style"] = 'style="background:lightgreen;"';
    } elseif ($data["value"] >= 65) {
        $record["value_style"] = 'style="background:yellow;"';
    } elseif ($data["value"] >= 55) {
        $record["value_style"] = 'style="background:orange;"';
    } else {
        $record["value_style"] = 'style="background:red;"';
    }
} else {
    $record["value_style"] = ''; 
}


// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>