<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_mfr_status_report  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeShowList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		function BeforeShowList(&$xt, &$templatefile, &$pageObject)
{
    // Initial values for pagination
    $pageNumber = 1;
    $showPerPage = 20;

    // Clear existing data in MFR_Operational_Status table
    DB::Exec("TRUNCATE TABLE MFR_Operational_Status");

    do {
        // Fetch data from the API
        $apiUrl = "https://mfr-be.k8s.sandboxaddis.com/api/Report/Counts";
        $ch = curl_init();

        curl_setopt_array($ch, array(
            CURLOPT_URL => $apiUrl,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => 'POST',
            CURLOPT_POSTFIELDS => json_encode(array('pageNumber' => $pageNumber, 'showPerPage' => $showPerPage)),
            CURLOPT_HTTPHEADER => array(
                'Accept: application/json, text/plain, */*',
                'Accept-Language: en-US,en;q=0.9',
                'sec-ch-ua-platform: "Windows"',
                'Cache-Control: no-cache',
                'Content-Length: ' . strlen(json_encode(array('pageNumber' => $pageNumber, 'showPerPage' => $showPerPage))),
                'Content-Type: application/json',
                'Origin: https://mfrv2.moh.gov.et',
                'Pragma: no-cache',
                'Referer: https://mfrv2.moh.gov.et/',
                'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126"',
                'sec-ch-ua-mobile: ?0'
            ),
        ));

        $response = curl_exec($ch);
        curl_close($ch);

        if ($response === false) {
            echo 'Error fetching the API data.';
            return;
        }

        $data = json_decode($response, true);

        // Insert data into MFR_Operational_Status table
        foreach ($data['model'] as $item) {
            $operationalStatus = DB::PrepareString($item['operationalStatus']);
            $status = DB::PrepareString($item['status']);
            $count = (int)$item['count'];

            $sql = "INSERT INTO MFR_Operational_Status (OperationalStatus, Status, Count) VALUES ($operationalStatus, $status, $count)";
            DB::Exec($sql);
        }

        // Check if there are more pages to fetch
        $totalCount = $data['model'][0]['totalCount'];
        $pageCount = ceil($totalCount / $showPerPage);
        $pageNumber++;

    } while ($pageNumber <= $pageCount);

    echo "Data successfully inserted into MFR_Operational_Status table.";
}

;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>