<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_mfr_reporting  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		// Fetch data from the API
$apiUrl = "https://mfr-be.k8s.sandboxaddis.com/api/report/dashboard?All";
$response = file_get_contents($apiUrl);

if ($response === false) {
    echo 'Error fetching the API data.';
    return;
}

$data = json_decode($response, true);

// Clear existing data in MFR_Reporting table
DB::Exec("TRUNCATE TABLE MFR_Reporting");

// Insert data into MFR_Reporting table
foreach ($data['model'] as $item) {
    $type = $item['type'];
    $name = $item['name'];
    $count = (int)$item['count'];

    $sql = "INSERT INTO MFR_Reporting (Type, Name, Count) VALUES ('$type', '$name', $count)";
    DB::Exec($sql);
}

//echo "Data successfully inserted into MFR_Reporting table.";

;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>