<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_moh_indicators_data_report  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessReport"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
				// Report page: Before process
function BeforeProcessReport($pageObject)
{

		if ($data["data_source_id"] == 1) { 
    if ($data["value"] >= 95) {
        $record["$"] = 'style="background:green;"';
    } elseif ($data["value"] >= 80) {
        $record["value_style"] = 'style="background:lightgreen;"';
    } elseif ($data["value"] >= 65) {
        $record["value_style"] = 'style="background:yellow;"';
    } elseif ($data["value"] >= 55) {
        $record["value_style"] = 'style="background:orange;"';
    } else {
        $record["value_style"] = 'style="background:red;"';
    }
} else {
    $record["value_style"] = ''; 
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessReport

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>