<?php
require_once(getabspath("classes/cipherer.php"));



$tdataprism_dashboard = array();
$tdataprism_dashboard[".ShortName"] = "prism_dashboard";

$tdataprism_dashboard[".pagesByType"] = my_json_decode( "{\"dashboard\":[\"PRISM_Dashboard\"]}" );
$tdataprism_dashboard[".originalPagesByType"] = $tdataprism_dashboard[".pagesByType"];
$tdataprism_dashboard[".pages"] = types2pages( my_json_decode( "{\"dashboard\":[\"PRISM_Dashboard\"]}" ) );
$tdataprism_dashboard[".originalPages"] = $tdataprism_dashboard[".pages"];
$tdataprism_dashboard[".defaultPages"] = my_json_decode( "{\"dashboard\":\"PRISM_Dashboard\"}" );
$tdataprism_dashboard[".originalDefaultPages"] = $tdataprism_dashboard[".defaultPages"];


//	field labels
$fieldLabelsprism_dashboard = array();
$pageTitlesprism_dashboard = array();

if(mlang_getcurrentlang()=="English")
{
	$fieldLabelsprism_dashboard["English"] = array();
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_CompletionDate"] = "Completion Date";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_SubmissionDate"] = "Submission Date";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_starttime"] = "Starttime";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_endtime"] = "Endtime";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_deviceid"] = "Deviceid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_subscriberid"] = "Subscriberid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_simid"] = "Simid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_devicephonenum"] = "Devicephonenum";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_username"] = "Username";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_duration"] = "Duration";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_caseid"] = "Caseid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT101"] = "OBAT101";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT102"] = "OBAT102";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT103"] = "OBAT103";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT104"] = "OBAT104";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_admin_lvl"] = "Admin Lvl";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT105"] = "OBAT105";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT106"] = "OBAT106";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT107"] = "OBAT107";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT108"] = "OBAT108";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_siteid"] = "Siteid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT109f"] = "OBAT109f";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT110f"] = "OBAT110f";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT111"] = "OBAT111";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT112"] = "OBAT112";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD1"] = "DD1";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD2"] = "DD2";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD3a"] = "DD3a";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD3b"] = "DD3b";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD4a"] = "DD4a";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD4b"] = "DD4b";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5a"] = "DD5a";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5b"] = "DD5b";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_1"] = "DD5c 1";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_2"] = "DD5c 2";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_3"] = "DD5c 3";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_5"] = "DD5c 5";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_96"] = "DD5c 96";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5co"] = "DD5co";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_SubmissionDate"] = "Submission Date";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_starttime"] = "Starttime";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_endtime"] = "Endtime";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_deviceid"] = "Deviceid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_subscriberid"] = "Subscriberid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_simid"] = "Simid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_devicephonenum"] = "Devicephonenum";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_username"] = "Username";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_duration"] = "Duration";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_caseid"] = "Caseid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_DQ104"] = "DQ104";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ101"] = "Intvwr Vst DQ101";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ102"] = "Intvwr Vst DQ102";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ102_Other"] = "Intvwr Vst DQ102 Other";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ105"] = "Distr Unit Id DQ105";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ106"] = "Distr Unit Id DQ106";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ106_Other"] = "Distr Unit Id DQ106 Other";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ108"] = "Distr Unit Id DQ108";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_siteid"] = "Siteid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_national_prism_woreda_level_diagnostic_gen_info_DQ109"] = "Gen Info DQ109";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_CompletionDate"] = "Completion Date";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_SubmissionDate"] = "Submission Date";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_starttime"] = "Starttime";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_endtime"] = "Endtime";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_deviceid"] = "Deviceid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_subscriberid"] = "Subscriberid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_simid"] = "Simid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_devicephonenum"] = "Devicephonenum";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_username"] = "Username";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_duration"] = "Duration";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_caseid"] = "Caseid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ104"] = "FQ104";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ101"] = "FQ101";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ102"] = "FQ102";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ103"] = "FQ103";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ105"] = "FQ105";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ106"] = "FQ106";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ107"] = "FQ107";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ108"] = "FQ108";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_siteid"] = "Siteid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ109"] = "FQ109";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ110"] = "FQ110";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ111"] = "FQ111";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ112"] = "FQ112";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ113"] = "FQ113";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_CompletionDate"] = "Completion Date";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_SubmissionDate"] = "Submission Date";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_starttime"] = "Starttime";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_endtime"] = "Endtime";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_deviceid"] = "Deviceid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_subscriberid"] = "Subscriberid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_simid"] = "Simid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_devicephonenum"] = "Devicephonenum";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_username"] = "Username";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_duration"] = "Duration";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_caseid"] = "Caseid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_FOC105"] = "FOC105";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_FOC101"] = "FOC101";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_FOC102"] = "FOC102";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_FOC103"] = "FOC103";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_FOC104"] = "FOC104";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_admin_lvl"] = "Admin Lvl";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_admin_lvl2"] = "Admin Lvl2";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_FOC106"] = "FOC106";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_FOC107"] = "FOC107";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_FOC108"] = "FOC108";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_siteid"] = "Siteid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_FOC109f"] = "FOC109f";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_FOC110f"] = "FOC110f";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_facility_office_checklist_FOC111"] = "FOC111";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_CompletionDate"] = "Completion Date";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_SubmissionDate"] = "Submission Date";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_starttime"] = "Starttime";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_endtime"] = "Endtime";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_deviceid"] = "Deviceid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_subscriberid"] = "Subscriberid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_simid"] = "Simid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_devicephonenum"] = "Devicephonenum";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_username"] = "Username";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_duration"] = "Duration";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_caseid"] = "Caseid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ104"] = "HPQ104";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ101"] = "HPQ101";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ102"] = "HPQ102";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ105"] = "HPQ105";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ106"] = "HPQ106";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ106_Other"] = "HPQ106 Other";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ107"] = "HPQ107";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ108"] = "HPQ108";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_siteid"] = "Siteid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ109"] = "HPQ109";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ110"] = "HPQ110";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_CompletionDate"] = "Completion Date";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_SubmissionDate"] = "Submission Date";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_starttime"] = "Starttime";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_endtime"] = "Endtime";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_deviceid"] = "Deviceid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_subscriberid"] = "Subscriberid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_simid"] = "Simid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_devicephonenum"] = "Devicephonenum";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_username"] = "Username";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_duration"] = "Duration";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_caseid"] = "Caseid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_OBAT101"] = "OBAT101";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_OBAT102"] = "OBAT102";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_OBAT104"] = "OBAT104";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_admin_lvl"] = "Admin Lvl";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_OBAT105"] = "OBAT105";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_OBAT106"] = "OBAT106";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_OBAT107"] = "OBAT107";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_OBAT108"] = "OBAT108";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_siteid"] = "Siteid";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_OBAT109f"] = "OBAT109f";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_OBAT110f"] = "OBAT110f";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_OBAT111"] = "OBAT111";
	$fieldLabelsprism_dashboard["English"]["public_ethprism_organizational_and_behavioral_assessment_OBAT112"] = "OBAT112";
}

/*
//	search fields
$tdataprism_dashboard[".searchFields"] = array();
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"CompletionDate" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_CompletionDate"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"SubmissionDate" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_SubmissionDate"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"starttime" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_starttime"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"endtime" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_endtime"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"deviceid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_deviceid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"subscriberid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_subscriberid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"simid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_simid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"devicephonenum" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_devicephonenum"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"username" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_username"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"duration" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_duration"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"caseid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_caseid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"OBAT101" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT101"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"OBAT102" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT102"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"OBAT103" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT103"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"OBAT104" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT104"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"admin_lvl" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_admin_lvl"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"OBAT105" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT105"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"OBAT106" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT106"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"OBAT107" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT107"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"OBAT108" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT108"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"siteid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_siteid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"OBAT109f" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT109f"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"OBAT110f" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT110f"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"OBAT111" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT111"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"OBAT112" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_OBAT112"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD1" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD1"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD2" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD2"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD3a" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD3a"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD3b" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD3b"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD4a" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD4a"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD4b" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD4b"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD5a" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5a"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD5b" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5b"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD5c_1" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_1"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD5c_2" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_2"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD5c_3" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_3"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD5c_5" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_5"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD5c_96" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_96"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_additional_organizational_and_behavioral_assessment", "field"=>"DD5co" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_additional_organizational_and_behavioral_assessment_DD5co"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"SubmissionDate" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_SubmissionDate"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"starttime" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_starttime"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"endtime" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_endtime"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"deviceid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_deviceid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"subscriberid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_subscriberid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"simid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_simid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"devicephonenum" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_devicephonenum"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"username" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_username"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"duration" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_duration"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"caseid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_caseid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"DQ104" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_DQ104"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"intvwr_vst_DQ101" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ101"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"intvwr_vst_DQ102" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ102"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"intvwr_vst_DQ102_Other" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ102_Other"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"distr_unit_id_DQ105" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ105"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"distr_unit_id_DQ106" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ106"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"distr_unit_id_DQ106_Other" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ106_Other"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"distr_unit_id_DQ108" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ108"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"siteid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_siteid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_national_prism_woreda_level_diagnostic", "field"=>"gen_info_DQ109" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_national_prism_woreda_level_diagnostic_gen_info_DQ109"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"CompletionDate" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_CompletionDate"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"SubmissionDate" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_SubmissionDate"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"starttime" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_starttime"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"endtime" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_endtime"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"deviceid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_deviceid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"subscriberid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_subscriberid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"simid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_simid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"devicephonenum" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_devicephonenum"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"username" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_username"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"duration" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_duration"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"caseid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_caseid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ104" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ104"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ101" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ101"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ102" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ102"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ103" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ103"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ105" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ105"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ106" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ106"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ107" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ107"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ108" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ108"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"siteid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_siteid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ109" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ109"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ110" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ110"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ111" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ111"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ112" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ112"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_level_rhis_performance_diagnostic", "field"=>"FQ113" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_level_rhis_performance_diagnostic_FQ113"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"CompletionDate" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_CompletionDate"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"SubmissionDate" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_SubmissionDate"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"starttime" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_starttime"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"endtime" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_endtime"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"deviceid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_deviceid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"subscriberid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_subscriberid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"simid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_simid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"devicephonenum" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_devicephonenum"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"username" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_username"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"duration" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_duration"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"caseid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_caseid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"FOC105" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_FOC105"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"FOC101" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_FOC101"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"FOC102" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_FOC102"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"FOC103" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_FOC103"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"FOC104" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_FOC104"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"admin_lvl" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_admin_lvl"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"admin_lvl2" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_admin_lvl2"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"FOC106" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_FOC106"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"FOC107" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_FOC107"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"FOC108" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_FOC108"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"siteid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_siteid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"FOC109f" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_FOC109f"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"FOC110f" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_FOC110f"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_facility_office_checklist", "field"=>"FOC111" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_facility_office_checklist_FOC111"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"CompletionDate" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_CompletionDate"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"SubmissionDate" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_SubmissionDate"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"starttime" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_starttime"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"endtime" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_endtime"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"deviceid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_deviceid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"subscriberid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_subscriberid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"simid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_simid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"devicephonenum" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_devicephonenum"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"username" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_username"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"duration" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_duration"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"caseid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_caseid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"HPQ104" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ104"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"HPQ101" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ101"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"HPQ102" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ102"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"HPQ105" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ105"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"HPQ106" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ106"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"HPQ106_Other" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ106_Other"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"HPQ107" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ107"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"HPQ108" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ108"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"siteid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_siteid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"HPQ109" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ109"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_healthpost_level_rhis_performance_diagnostic", "field"=>"HPQ110" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ110"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"CompletionDate" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_CompletionDate"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"SubmissionDate" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_SubmissionDate"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"starttime" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_starttime"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"endtime" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_endtime"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"deviceid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_deviceid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"subscriberid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_subscriberid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"simid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_simid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"devicephonenum" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_devicephonenum"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"username" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_username"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"duration" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_duration"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"caseid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_caseid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"OBAT101" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_OBAT101"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"OBAT102" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_OBAT102"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"OBAT104" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_OBAT104"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"admin_lvl" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_admin_lvl"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"OBAT105" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_OBAT105"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"OBAT106" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_OBAT106"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"OBAT107" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_OBAT107"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"OBAT108" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_OBAT108"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"siteid" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_siteid"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"OBAT109f" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_OBAT109f"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"OBAT110f" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_OBAT110f"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"OBAT111" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_OBAT111"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"public.ethprism_organizational_and_behavioral_assessment", "field"=>"OBAT112" );
$tdataprism_dashboard[".searchFields"]["public_ethprism_organizational_and_behavioral_assessment_OBAT112"] = $dashField;

// all search fields
$tdataprism_dashboard[".allSearchFields"] = array();
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_CompletionDate";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_SubmissionDate";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_starttime";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_endtime";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_deviceid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_subscriberid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_simid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_devicephonenum";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_username";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_duration";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_caseid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT101";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT102";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT103";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT104";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_admin_lvl";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT105";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT106";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT107";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT108";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_siteid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT109f";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT110f";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT111";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT112";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD1";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD2";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD3a";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD3b";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD4a";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD4b";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5a";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5b";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_1";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_2";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_3";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_5";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_96";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5co";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_SubmissionDate";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_starttime";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_endtime";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_deviceid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_subscriberid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_simid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_devicephonenum";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_username";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_duration";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_caseid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_DQ104";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ101";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ102";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ102_Other";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ105";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ106";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ106_Other";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ108";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_siteid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_national_prism_woreda_level_diagnostic_gen_info_DQ109";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_CompletionDate";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_SubmissionDate";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_starttime";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_endtime";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_deviceid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_subscriberid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_simid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_devicephonenum";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_username";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_duration";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_caseid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ104";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ101";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ102";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ103";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ105";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ106";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ107";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ108";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_siteid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ109";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ110";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ111";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ112";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_level_rhis_performance_diagnostic_FQ113";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_CompletionDate";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_SubmissionDate";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_starttime";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_endtime";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_deviceid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_subscriberid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_simid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_devicephonenum";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_username";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_duration";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_caseid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_FOC105";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_FOC101";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_FOC102";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_FOC103";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_FOC104";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_admin_lvl";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_admin_lvl2";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_FOC106";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_FOC107";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_FOC108";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_siteid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_FOC109f";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_FOC110f";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_facility_office_checklist_FOC111";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_CompletionDate";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_SubmissionDate";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_starttime";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_endtime";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_deviceid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_subscriberid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_simid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_devicephonenum";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_username";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_duration";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_caseid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ104";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ101";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ102";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ105";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ106";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ106_Other";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ107";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ108";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_siteid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ109";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ110";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_CompletionDate";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_SubmissionDate";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_starttime";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_endtime";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_deviceid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_subscriberid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_simid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_devicephonenum";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_username";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_duration";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_caseid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_OBAT101";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_OBAT102";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_OBAT104";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_admin_lvl";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_OBAT105";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_OBAT106";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_OBAT107";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_OBAT108";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_siteid";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_OBAT109f";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_OBAT110f";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_OBAT111";
$tdataprism_dashboard[".allSearchFields"][] = "public_ethprism_organizational_and_behavioral_assessment_OBAT112";

// good like search fields
$tdataprism_dashboard[".googleLikeFields"] = array();
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_CompletionDate";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_SubmissionDate";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_starttime";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_endtime";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_deviceid";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_subscriberid";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_simid";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_devicephonenum";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_username";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_duration";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_caseid";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT101";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT102";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT103";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT104";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_admin_lvl";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT105";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT106";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT107";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT108";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_siteid";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT109f";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT110f";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT111";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_OBAT112";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD1";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD2";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD3a";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD3b";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD4a";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD4b";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5a";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5b";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_1";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_2";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_3";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_5";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_96";
$tdataprism_dashboard[".googleLikeFields"][] = "public_ethprism_additional_organizational_and_behavioral_assessment_DD5co";
*/

/*
$tdataprism_dashboard[".dashElements"] = array();

	$dbelement = array( "elementName" => "public_ethprism_additional_organizational_and_behavioral_assessment_grid", "table" => "public.ethprism_additional_organizational_and_behavioral_assessment",
		 "pageName" => "","type" => 0);
	$dbelement["cellName"] = "";

		$dbelement["reload"] = 60;
		$dbelement["width"] = 800;
		$dbelement["height"] = 600;
	

	$tdataprism_dashboard[".dashElements"][] = $dbelement;
	$dbelement = array( "elementName" => "public_ethprism_national_prism_woreda_level_diagnostic_grid", "table" => "public.ethprism_national_prism_woreda_level_diagnostic",
		 "pageName" => "","type" => 0);
	$dbelement["cellName"] = "";

		$dbelement["reload"] = 60;
		$dbelement["width"] = 800;
		$dbelement["height"] = 600;
	

	$tdataprism_dashboard[".dashElements"][] = $dbelement;
	$dbelement = array( "elementName" => "public_ethprism_facility_level_rhis_performance_diagnostic_grid", "table" => "public.ethprism_facility_level_rhis_performance_diagnostic",
		 "pageName" => "","type" => 0);
	$dbelement["cellName"] = "";

		$dbelement["reload"] = 60;
		$dbelement["width"] = 800;
		$dbelement["height"] = 600;
	

	$tdataprism_dashboard[".dashElements"][] = $dbelement;
	$dbelement = array( "elementName" => "public_ethprism_facility_office_checklist_grid", "table" => "public.ethprism_facility_office_checklist",
		 "pageName" => "","type" => 0);
	$dbelement["cellName"] = "";

		$dbelement["reload"] = 60;
		$dbelement["width"] = 800;
		$dbelement["height"] = 600;
	

	$tdataprism_dashboard[".dashElements"][] = $dbelement;
	$dbelement = array( "elementName" => "public_ethprism_healthpost_level_rhis_performance_diagnostic_grid", "table" => "public.ethprism_healthpost_level_rhis_performance_diagnostic",
		 "pageName" => "","type" => 0);
	$dbelement["cellName"] = "";

		$dbelement["reload"] = 60;
		$dbelement["width"] = 800;
		$dbelement["height"] = 600;
	

	$tdataprism_dashboard[".dashElements"][] = $dbelement;
	$dbelement = array( "elementName" => "public_ethprism_organizational_and_behavioral_assessment_grid", "table" => "public.ethprism_organizational_and_behavioral_assessment",
		 "pageName" => "","type" => 0);
	$dbelement["cellName"] = "";

		$dbelement["reload"] = 60;
		$dbelement["width"] = 800;
		$dbelement["height"] = 600;
	

	$tdataprism_dashboard[".dashElements"][] = $dbelement;
*/
$tdataprism_dashboard[".shortTableName"] = "prism_dashboard";
$tdataprism_dashboard[".entityType"] = 4;




$tdataprism_dashboard[".hasEvents"] = false;


$tdataprism_dashboard[".tableType"] = "dashboard";


	
$tdataprism_dashboard[".addPageEvents"] = false;

$tdataprism_dashboard[".isUseAjaxSuggest"] = true;

$tables_data["PRISM Dashboard"]=&$tdataprism_dashboard;
$field_labels["PRISM_Dashboard"] = &$fieldLabelsprism_dashboard;
$page_titles["PRISM_Dashboard"] = &$pageTitlesprism_dashboard;

?>