<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_public_mfr_facilities_register_chart  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeQueryChart"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Chart page: Before SQL query
function BeforeQueryChart(&$strSQL, &$strWhereClause, &$strOrderBy)
{

		
$strWhereCaluse = "[Session] = '".$_SESSION["SignedOnUser"]."'";

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeQueryChart

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>