<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_regions  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		
//addNotification( "New Region added: ".$values["name"] , "New Region", "fa-location", makePageLink( "regions", "view", $keys));

addNotification( "New Region added: ".$values["name"], "New Region", "fa-envelope", 
GetTableLink( "regions", "view", "editid1=".$keys["region_id"]));

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		//addNotification( "Region Updated: ".$values["name"] , "New Region", "fa-location", makePageLink( "regions", "view", $keys));

    // Define the field to highlight in the notification
   // $fieldName = "name";  // Replace with the actual field name you want to show

    // Always show both the old and new values
addNotification( "Region Value Updated To: ".$values["name"], " Region", "fa-edit", 
GetTableLink( "regions", "view", "editid1=".$keys["region_id"]));



// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
