<?php
$securitySettings_var = array( 'providers' => array(  ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'kvYEBQlfUenuNJxX2FfZ',
'JWTSecret' => 'ccb9PA7y4IwiyTiW5U83' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 0,
'hashAlgorithm' => 0,
'registerPage' => false ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => '',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'localhost',
'SMTPPort' => 25,
'SMTPUser' => '',
'SMTPPassword' => '',
'securityProtocol' => 0 ),
'advancedSecurity' => array( 'allowGuestLogin' => false ),
'auditAndLocking' => array( 'loggingTable' => array(  ),
'lockingTable' => array(  ),
'tables' => array(  ),
'loggingMode' => 0,
'loggingFile' => 'audit.log',
'logSecurityActions' => false,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'HISPMD_V01',
'loginDataSource' => '',
'loginForm' => 3,
'dynamicPermissions' => false,
'dpTablePrefix' => '',
'dpTableConnId' => '',
'hardcodedLogin' => false,
'enabled' => false,
'advancedSecurityAvailable' => false,
'userGroupsAvailable' => false,
'adOnlyLogin' => false,
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array(  ),
'notifications' => array(  ) );
?>