<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'addToBottom' => false,
'delete' => true,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'user_id' => array( 'totalsType' => '' ),
'comment' => array( 'totalsType' => '' ),
'created_date' => array( 'totalsType' => '' ),
's_id' => array( 'totalsType' => '' ),
'status' => array( 'totalsType' => '' ),
'images' => array( 'totalsType' => '' ),
'name' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'editlink' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'editlink',
'comment',
'id',
'images',
's_id',
'user_id',
'created_date' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'images' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'created_date' => array( 'simple_grid_field15',
'simple_grid_field3' ),
'comment' => array( 'grid_field_label',
'grid_field' ),
's_id' => array( 'grid_field_label1',
'grid_field1' ),
'user_id' => array( 'grid_field2',
'grid_field_label2' ),
'images' => array( 'grid_field3',
'grid_field_label3' ),
'editlink' => array( 'grid_field6' ),
'id' => array( 'grid_field4' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'snippet' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'admin_header',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'delete',
'list_options',
'loginform_login',
'username_button' ),
'grid' => array( 'grid_field_label2',
'grid_field2',
'simple_grid_field15',
'simple_grid_field3',
'grid_checkbox_head',
'grid_checkbox',
'details_found',
'page_size',
'sgb_admin_comments_filter',
'sgb_admin_comments_mark',
'grid_field_label',
'grid_field6',
'grid_field',
'grid_field4',
'grid_field_label1',
'grid_field1',
'grid_field_label3',
'grid_field3' ),
'top' => array(  ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'snippet' => 'above-grid',
'pagination' => 'below-grid',
'admin_header' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'delete' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field3' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'details_found' => 'grid',
'page_size' => 'grid',
'sgb_admin_comments_filter' => 'grid',
'sgb_admin_comments_mark' => 'grid',
'grid_field_label' => 'grid',
'grid_field6' => 'grid',
'grid_field' => 'grid',
'grid_field4' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid' ),
'itemLocations' => array( 'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'details_found' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'page_size' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'sgb_admin_comments_filter' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'sgb_admin_comments_mark' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'breadcrumb' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'snippet' => array( 'snippet',
'sgb_admin_comments_filter',
'sgb_admin_comments_mark' ),
'pagination' => array( 'pagination' ),
'grid_field_label' => array( 'simple_grid_field15',
'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label3' ),
'grid_field' => array( 'simple_grid_field3',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field3',
'grid_field6',
'grid_field4' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'details_found' => array( 'details_found' ),
'page_size' => array( 'page_size' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'-' => array( '-3',
'-' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'menu' => array( 'menu' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'text' => array( 'admin_header' ),
'delete' => array( 'delete' ),
'search_panel' => array( 'search_panel' ),
'search_panel_field' => array( 'search_panel_field' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'delete_selected' => array( 'delete_selected' ),
'breadcrumb' => array( 'breadcrumb' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field5' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'sgb_admin_comments_filter',
'sgb_admin_comments_mark' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'images_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 3,
4,
5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_found',
'page_size' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'comment_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 's_id_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'user_id_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'created_date_fieldheadercolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'editlink_fieldcolumn',
'comment_fieldcolumn',
'id_fieldcolumn' ),
'items' => array( 'grid_field6',
'grid_field',
'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'images_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 's_id_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array( 'user_id_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array( 'created_date_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 6,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'snippet' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'admin_header',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'delete' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field5',
'colspan' => 2 ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field',
'colspan' => 3 ) ) ),
array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field4' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field4' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field4' ) ) ) ),
'cells' => array( 'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'align' => 'left',
'field' => 'user_id',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'align' => 'left',
'field' => 'user_id',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field15' ),
'align' => 'left',
'field' => 'created_date',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'align' => 'left',
'field' => 'created_date',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'headcell_field' => array( 'model' => 'headcell_checkbox',
'items' => array( 'details_found',
'page_size' ),
'align' => 'right' ),
'headcell_field5' => array( 'model' => 'headcell_checkbox',
'items' => array( 'sgb_admin_comments_filter',
'sgb_admin_comments_mark' ),
'align' => 'left' ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'customCSS' => '@media (min-width: 767px) {
   :host {
         width:30% !important;
    }
}
@media (max-width: 767px) {
   :host {
         width:100% !important;
    }
 
}
',
'field' => 'comment',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6',
'grid_field',
'grid_field4' ),
'customCSS' => '@media (min-width: 767px) {
   :host {
         width:30% !important;
    }
}
@media (max-width: 767px) {
   :host {
         width:100% !important;
    }
 
}
',
'align' => 'left',
'field' => 'editlink',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ),
'customCSS' => '@media (min-width: 767px) {
   :host {
         width:30% !important;
    }
}
@media (max-width: 767px) {
   :host {
         width:100% !important;
    }
 
}
' ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'customCSS' => '
@media (min-width: 767px) {
   :host {
         width:20% !important;
    }
}
@media (max-width: 767px) {
   :host {
         width:100% !important;
    }
 
}',
'field' => 's_id',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'align' => 'left',
'customCSS' => '
@media (min-width: 767px) {
   :host {
         width:20% !important;
    }
}
@media (max-width: 767px) {
   :host {
         width:100% !important;
    }
 
}',
'field' => 's_id',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ),
'customCSS' => '
@media (min-width: 767px) {
   :host {
         width:20% !important;
    }
}
@media (max-width: 767px) {
   :host {
         width:100% !important;
    }
 
}' ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'field' => 'images',
'columnName' => 'field' ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'images',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'snippet' => array( 'type' => 'snippet',
'eventId' => 'sgb_admin_mod_navigation',
'label' => array( 'text' => 'sgb_admin_mod_navigation',
'type' => 0 ) ),
'pagination' => array( 'type' => 'pagination' ),
'simple_grid_field15' => array( 'type' => 'grid_field_label',
'field' => 'created_date',
'clickSort' => false,
'label' => array( 'field' => 'created_date',
'table' => 'sgb_admin_comments',
'type' => 3 ) ),
'simple_grid_field3' => array( 'field' => 'created_date',
'type' => 'grid_field',
'clickSort' => false,
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'details_found' => array( 'type' => 'details_found' ),
'page_size' => array( 'type' => 'page_size' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'comment',
'label' => array( 'field' => 'comment',
'table' => 'sgb_admin_comments',
'type' => 3 ) ),
'grid_field' => array( 'field' => 'comment',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 's_id',
'label' => array( 'field' => 's_id',
'table' => 'sgb_admin_comments',
'type' => 3 ) ),
'grid_field1' => array( 'field' => 's_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'-3' => array( 'type' => '-' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'menu' => array( 'type' => 'menu' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'admin_header' => array( 'type' => 'text',
'label' => array( 'text' => 'Board Admin Panel',
'type' => 0 ),
'editedByRte' => false ),
'grid_field2' => array( 'field' => 'user_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'user_id',
'label' => array( 'field' => 'user_id',
'table' => 'sgb_admin_comments',
'type' => 3 ) ),
'delete' => array( 'type' => 'delete',
'customCSS' => ':host {
  display:none;
}
' ),
'sgb_admin_comments_filter' => array( 'eventId' => 'sgb_admin_comments_filter',
'label' => array( 'text' => 'sgb_admin_comments_filter',
'type' => 0 ),
'type' => 'snippet' ),
'sgb_admin_comments_mark' => array( 'eventId' => 'sgb_admin_comments_mark',
'label' => array( 'text' => 'sgb_admin_comments_mark',
'type' => 0 ),
'type' => 'snippet' ),
'grid_field3' => array( 'field' => 'images',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'images' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field' ) ),
'search_panel_field' => array( 'field' => 'images',
'type' => 'search_panel_field',
'required' => false ),
'grid_field6' => array( 'field' => 'editlink',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'delete_selected',
'-',
'show_search_panel',
'hide_search_panel' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'-' => array( 'type' => '-' ),
'grid_field4' => array( 'field' => 'id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>