<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'editInPopup' => null,
'clickSort' => false,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'allDetails' => array( 'linkType' => 2 ),
'details' => array( 'sgb_comments' => array( 'displayPreview' => 2,
'previewPageId' => '',
'showCount' => false,
'badgeColor' => '',
'hideEmptyChild' => false,
'hideEmptyPreview' => null,
'showProceedLink' => null,
'printDetails' => false ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => false,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'suggested_by' => array( 'totalsType' => '' ),
'status' => array( 'totalsType' => '' ),
'created_date' => array( 'totalsType' => '' ),
'upvoted_date' => array( 'totalsType' => '' ),
'suggestion' => array( 'totalsType' => '' ),
'vote' => array( 'totalsType' => '' ),
'categoryid' => array( 'totalsType' => '' ),
'title' => array( 'totalsType' => '' ),
'comments' => array( 'totalsType' => '' ),
'images' => array( 'totalsType' => '' ),
'name' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'pinned' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'vote',
'title',
'suggested_by',
'created_date',
'upvoted_date',
'comments',
'pinned',
'status',
'categoryid' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'suggested_by' => array( 'simple_grid_field1' ),
'status' => array( 'simple_grid_field2' ),
'vote' => array( 'grid_field1' ),
'title' => array( 'grid_field' ),
'created_date' => array( 'grid_field2' ),
'upvoted_date' => array( 'grid_field3' ),
'comments' => array( 'grid_field4' ),
'categoryid' => array( 'sgb_category' ),
'pinned' => array( 'pinned' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => true,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'pagination' ),
'supertop' => array( 'logo',
'sgb_admin_notification',
'loginform_login',
'username_button' ),
'left' => array(  ),
'top' => array( 'sgb_top_new_buttons',
'sgb_status_select',
'sgb_category_select',
'sgb_showdeleted',
'simple_search',
'add',
'sgb_promo' ),
'grid' => array( 'grid_field1',
'grid_field',
'simple_grid_field1',
'grid_field2',
'point',
'grid_field3',
'text',
'grid_field4',
'break1',
'pinned',
'simple_grid_field2',
'sgb_category',
'grid_view' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array( 'pagination' ),
'left' => array(  ) ),
'itemForms' => array( 'pagination' => 'below-grid',
'logo' => 'supertop',
'sgb_admin_notification' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'sgb_top_new_buttons' => 'top',
'sgb_status_select' => 'top',
'sgb_category_select' => 'top',
'sgb_showdeleted' => 'top',
'simple_search' => 'top',
'add' => 'top',
'sgb_promo' => 'top',
'grid_field1' => 'grid',
'grid_field' => 'grid',
'simple_grid_field1' => 'grid',
'grid_field2' => 'grid',
'point' => 'grid',
'grid_field3' => 'grid',
'text' => 'grid',
'grid_field4' => 'grid',
'break1' => 'grid',
'pinned' => 'grid',
'simple_grid_field2' => 'grid',
'sgb_category' => 'grid',
'grid_view' => 'grid' ),
'itemLocations' => array( 'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'point' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'text' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'break1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'pinned' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'sgb_category' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_top' ) ),
'itemVisiblity' => array( 'simple_search' => 3,
'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'pagination' => array( 'pagination' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field2',
'grid_field1',
'grid_field',
'grid_field2',
'grid_field3',
'grid_field4',
'sgb_category',
'pinned' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'logo' => array( 'logo' ),
'simple_search' => array( 'simple_search' ),
'-' => array( '-' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'add' => array( 'add' ),
'snippet' => array( 'sgb_promo',
'sgb_status_select',
'sgb_category_select',
'sgb_top_new_buttons',
'sgb_admin_notification',
'sgb_showdeleted' ),
'text' => array( 'break1',
'point',
'text' ),
'grid_view' => array( 'grid_view' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array( 'view_column' ),
'items' => array( 'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'vote_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_field',
'simple_grid_field1',
'grid_field2',
'point',
'grid_field3',
'text',
'grid_field4',
'break1',
'pinned',
'simple_grid_field2',
'sgb_category' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 1,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'list',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 4,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'sgb_admin_notification',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'sgb_top_new_buttons',
'sgb_status_select',
'sgb_category_select',
'sgb_showdeleted',
'simple_search',
'add' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'sgb_promo' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'vertical-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 2 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field',
'colspan' => 1,
'rowspan' => 1 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 2 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'grid_field1' ),
'align' => 'center',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  width:110px !important;
}
',
'field' => 'vote',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field',
'simple_grid_field1',
'grid_field2',
'point',
'grid_field3',
'text',
'grid_field4',
'break1',
'pinned',
'simple_grid_field2',
'sgb_category' ),
'field' => 'title',
'columnName' => 'field' ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_top' => array( 'model' => 'cell_top',
'items' => array( 'grid_view' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'pagination' => array( 'type' => 'pagination' ),
'simple_grid_field1' => array( 'field' => 'suggested_by',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field2' => array( 'field' => 'status',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field1' => array( 'field' => 'vote',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field' => array( 'field' => 'title',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'logo' => array( 'type' => 'logo' ),
'simple_search' => array( 'type' => 'simple_search' ),
'-' => array( 'type' => '-' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'add' => array( 'type' => 'add',
'label' => array( 'type' => 0,
'text' => 'Add suggestion' ),
'icon' => array( 'glyph' => '' ) ),
'sgb_promo' => array( 'eventId' => 'sgb_promo',
'label' => array( 'text' => 'sgb_promo',
'type' => 0 ),
'type' => 'snippet' ),
'sgb_status_select' => array( 'eventId' => 'sgb_status_select',
'label' => array( 'text' => 'sgb_status_select',
'type' => 0 ),
'type' => 'snippet' ),
'sgb_category_select' => array( 'eventId' => 'sgb_category_select',
'label' => array( 'text' => 'sgb_category_select',
'type' => 0 ),
'type' => 'snippet' ),
'sgb_top_new_buttons' => array( 'eventId' => 'sgb_suggestions_snippet',
'label' => array( 'text' => 'sgb_suggestions_snippet',
'type' => 0 ),
'type' => 'snippet' ),
'grid_field2' => array( 'field' => 'created_date',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'break1' => array( 'type' => 'text',
'label' => array( 'text' => '&nbsp;',
'type' => 0 ),
'editedByRte' => false ),
'grid_field3' => array( 'field' => 'upvoted_date',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field4' => array( 'field' => 'comments',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'sgb_category' => array( 'field' => 'categoryid',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'point' => array( 'type' => 'text',
'label' => array( 'text' => '•',
'type' => 0 ),
'editedByRte' => false,
'customCSS' => '/* Put  your custom CSS code here */

:host {
  margin-left:3px;
  margin-right:3px;
}
' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '•',
'type' => 0 ),
'editedByRte' => false,
'customCSS' => '/* Put  your custom CSS code here */

:host {
  margin-left:3px;
  margin-right:3px;
}
' ),
'sgb_admin_notification' => array( 'eventId' => 'sgb_admin_notification',
'label' => array( 'text' => 'sgb_admin_notification',
'type' => 0 ),
'type' => 'snippet' ),
'pinned' => array( 'field' => 'pinned',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'sgb_showdeleted' => array( 'eventId' => 'sgb_suggestions_showdeleted',
'label' => array( 'text' => 'sgb_suggestions_showdeleted',
'type' => 0 ),
'type' => 'snippet' ),
'grid_view' => array( 'type' => 'grid_view' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 11,
'pageAlign' => 'center',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>