<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'title',
'suggestion',
'status',
'newtitle',
'newstatus',
'newsuggestion',
'copyupvotes' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'title' => array( 'integrated_edit_field7' ),
'suggestion' => array( 'integrated_edit_field4' ),
'status' => array( 'integrated_edit_field' ),
'newtitle' => array( 'integrated_edit_field1' ),
'newstatus' => array( 'integrated_edit_field2' ),
'newsuggestion' => array( 'integrated_edit_field3' ),
'copyupvotes' => array( 'integrated_edit_field5' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array(  ),
'top' => array(  ),
'grid' => array( 'integrated_edit_field7',
'integrated_edit_field4',
'integrated_edit_field',
'text3',
'edit_save',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field5',
'text',
'text1',
'text2' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array(  ),
'top' => array(  ) ),
'itemForms' => array( 'integrated_edit_field7' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field' => 'grid',
'text3' => 'grid',
'edit_save' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field5' => 'grid',
'text' => 'grid',
'text1' => 'grid',
'text2' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'text3' => array( 'location' => 'grid',
'cellId' => 'c' ),
'edit_save' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'text' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'text1' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'text2' => array( 'location' => 'grid',
'cellId' => 'c8' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'integrated_edit_field' => array( 'integrated_edit_field7',
'integrated_edit_field4',
'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field5' ),
'edit_save' => array( 'edit_save' ),
'text' => array( 'text',
'text1',
'text2',
'text3' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7',
'integrated_edit_field4',
'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'text1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'text3',
'edit_save' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 7 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ) ) ),
array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field7',
'integrated_edit_field4',
'integrated_edit_field' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
border-radius: 4px;
}
' ),
'c' => array( 'model' => 'c3',
'items' => array( 'text3',
'edit_save' ),
'align' => 'right',
'orientation' => 'horizontal' ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3' ) ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'text' ),
'align' => 'left',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  border-bottom: 1px solid #e3e8ee;
}
' ),
'c7' => array( 'model' => 'c3',
'items' => array( 'text1' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
  border-top: 1px solid #e3e8ee;
}
' ),
'c8' => array( 'model' => 'c3',
'items' => array( 'text2' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'integrated_edit_field7' => array( 'field' => 'title',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'suggestion',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field' => array( 'field' => 'status',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'edit_save' => array( 'type' => 'edit_save',
'label' => array( 'type' => 0,
'text' => 'Split' ) ),
'integrated_edit_field1' => array( 'field' => 'newtitle',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'newtitle',
'table' => 'sgb_split',
'type' => 3 ),
'updateOnEdit' => false ),
'integrated_edit_field2' => array( 'field' => 'newstatus',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'newstatus',
'table' => 'sgb_split',
'type' => 3 ),
'updateOnEdit' => false ),
'integrated_edit_field3' => array( 'field' => 'newsuggestion',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'newsuggestion',
'table' => 'sgb_split',
'type' => 3 ),
'updateOnEdit' => false ),
'integrated_edit_field5' => array( 'field' => 'copyupvotes',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'copyupvotes',
'table' => 'sgb_split',
'type' => 3 ) ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'Edit the selected suggestion and create a new one.',
'type' => 0 ),
'editedByRte' => false ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'New suggestion',
'type' => 0 ),
'editedByRte' => false ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => '<span>You cannot undo changes once they\'re done.</span>',
'type' => 0 ),
'editedByRte' => false ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => '<span class=\'btn btn-default cancelmerge\'>Cancel</span>',
'type' => 0 ),
'editedByRte' => false,
'customCSS' => '/* Put  your custom CSS code here */

:host {
     float: right;
    margin-left: 10px;
}
' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>