<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => true,
'detailsAdd' => true,
'inlineEdit' => false,
'addToBottom' => true,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'viewInPopup' => null,
'clickSort' => false,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'master' => array( 'sgb_suggestions' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'user_id' => array( 'totalsType' => '' ),
'comment' => array( 'totalsType' => '' ),
'created_date' => array( 'totalsType' => '' ),
's_id' => array( 'totalsType' => '' ),
'status' => array( 'totalsType' => '' ),
'images' => array( 'totalsType' => '' ),
'admin_buttons' => array( 'totalsType' => '' ),
'user_buttons' => array( 'totalsType' => '' ),
'name' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'merged_info' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'created_date',
'user_id',
'comment',
'name',
'email',
'admin_buttons' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'status',
'images' ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'comment',
'name',
'email' ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'created_date' => array( 'grid_field2' ),
'user_id' => array( 'grid_field1' ),
'comment' => array( 'grid_field' ),
'admin_buttons' => array( 'sgb_comments_moderate_panel' ),
'name' => array( 'grid_field3' ),
'email' => array( 'grid_field4' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'pagination' ),
'left' => array( 'admin_header',
'expand_button',
'menu',
'search_panel',
'inline_save_all',
'inline_cancel_all',
'inline_add' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'logo',
'breadcrumb',
'sgb_admin_notification',
'loginform_login',
'username_button' ),
'grid' => array( 'grid_field2',
'grid_field1',
'add_comment_label',
'message_c_label',
'grid_field',
'sgb_comments_countheader',
'grid_edit',
'grid_inline_cancel',
'grid_inline_save',
'sgb_comments_moderate_panel',
'name_c_label',
'grid_field3',
'name_c_tooltip',
'email_c_label',
'grid_field4',
'email_c_tooltip' ),
'top' => array( 'master_info' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'pagination' => 'below-grid',
'admin_header' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'inline_save_all' => 'left',
'inline_cancel_all' => 'left',
'inline_add' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'logo' => 'supertop',
'breadcrumb' => 'supertop',
'sgb_admin_notification' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'grid_field2' => 'grid',
'grid_field1' => 'grid',
'add_comment_label' => 'grid',
'message_c_label' => 'grid',
'grid_field' => 'grid',
'sgb_comments_countheader' => 'grid',
'grid_edit' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_inline_save' => 'grid',
'sgb_comments_moderate_panel' => 'grid',
'name_c_label' => 'grid',
'grid_field3' => 'grid',
'name_c_tooltip' => 'grid',
'email_c_label' => 'grid',
'grid_field4' => 'grid',
'email_c_tooltip' => 'grid',
'master_info' => 'top' ),
'itemLocations' => array( 'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'add_comment_label' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'message_c_label' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'sgb_comments_countheader' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_inline_save' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'sgb_comments_moderate_panel' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'name_c_label' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'name_c_tooltip' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'email_c_label' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'email_c_tooltip' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'breadcrumb' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'pagination' => array( 'pagination' ),
'grid_field' => array( 'grid_field2',
'grid_field1',
'grid_field',
'sgb_comments_moderate_panel',
'grid_field3',
'grid_field4' ),
'text' => array( 'add_comment_label',
'message_c_label',
'name_c_label',
'name_c_tooltip',
'email_c_label',
'email_c_tooltip',
'admin_header' ),
'snippet' => array( 'sgb_comments_countheader',
'logo',
'sgb_admin_notification' ),
'grid_edit' => array( 'grid_edit' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ),
'grid_inline_save' => array( 'grid_inline_save' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'inline_add' => array( 'inline_add' ),
'inline_save_all' => array( 'inline_save_all' ),
'inline_cancel_all' => array( 'inline_cancel_all' ),
'master_info' => array( 'master_info' ),
'search_panel' => array( 'search_panel' ),
'menu' => array( 'menu' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'breadcrumb' => array( 'breadcrumb' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'sgb_comments_countheader',
'grid_edit' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_field2',
'grid_field1',
'add_comment_label',
'message_c_label',
'grid_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'name_c_label',
'grid_field3',
'name_c_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'email_c_label',
'grid_field4',
'email_c_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 3 ),
'tags' => array( 'admin_buttons_fieldcolumn' ),
'items' => array( 'sgb_comments_moderate_panel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 4 ),
'tags' => array( 'inline_cancel',
'inline_save' ),
'items' => array( 'grid_inline_cancel',
'grid_inline_save' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 6 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 1,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array( 'comment' ) ) );
			$pageArray = array( 'id' => 'list_admin',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1,
'rowspan' => 1 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'admin_header',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'inline_save_all',
'inline_cancel_all',
'inline_add' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
  display:none !important;
}
' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'logo',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'sgb_admin_notification',
'loginform_login',
'username_button' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'vertical-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 3 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_field',
'colspan' => 3 ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field6' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field2',
'colspan' => 3 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field1',
'colspan' => 3 ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 3 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2',
'grid_field1',
'add_comment_label',
'message_c_label',
'grid_field' ),
'orientation' => 'vertical',
'padding' => array( 'top' => '20px' ),
'field' => 'created_date',
'columnName' => 'field' ),
'cell_top' => array( 'model' => 'cell_top',
'items' => array( 'sgb_comments_countheader',
'grid_edit' ) ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_inline_cancel',
'grid_inline_save' ),
'align' => 'right' ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'sgb_comments_moderate_panel' ),
'field' => 'admin_buttons',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'name_c_label',
'grid_field3',
'name_c_tooltip' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
 width:48% !important;
}
',
'orientation' => 'vertical',
'field' => 'name',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'email_c_label',
'grid_field4',
'email_c_tooltip' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
 width:48% !important;
}
',
'orientation' => 'vertical',
'field' => 'email',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array(  ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
 width:4% !important;
}
' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'pagination' => array( 'type' => 'pagination' ),
'grid_field2' => array( 'field' => 'created_date',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'customCSS' => '/* Put  your custom CSS code here */

:host {
 font-style: italic;
}
' ),
'grid_field1' => array( 'field' => 'user_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'add_comment_label' => array( 'type' => 'text',
'label' => array( 'text' => '<i class=\'fa fa-plus-square-o\'></i>
<span>Add a comment</span>',
'type' => 0 ),
'editedByRte' => false ),
'message_c_label' => array( 'type' => 'text',
'label' => array( 'text' => 'Message',
'type' => 0 ),
'editedByRte' => false ),
'grid_field' => array( 'field' => 'comment',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => false,
'group_by' => true ),
'sgb_comments_countheader' => array( 'eventId' => 'sgb_comments_countheader',
'label' => array( 'text' => 'sgb_comments_countheader',
'type' => 0 ),
'type' => 'snippet' ),
'grid_edit' => array( 'type' => 'grid_edit',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  display:none;
}
',
'icon' => array( 'fa' => 'arrow-right' ) ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  display:none;
}
',
'icon' => array( 'fa' => 'external-link' ) ),
'grid_inline_save' => array( 'type' => 'grid_inline_save',
'label' => array( 'text' => 'Post Comment',
'type' => 0 ),
'tooltip' => array( 'type' => 0,
'text' => '' ),
'buttonStyle' => 'default',
'icon' => array( 'glyph' => '' ) ),
'sgb_comments_moderate_panel' => array( 'field' => 'admin_buttons',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'name_c_label' => array( 'type' => 'text',
'label' => array( 'text' => 'Name',
'type' => 0 ),
'editedByRte' => false ),
'grid_field3' => array( 'field' => 'name',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => false ),
'name_c_tooltip' => array( 'type' => 'text',
'label' => array( 'text' => '* Your name will be publicly visible',
'type' => 0 ),
'editedByRte' => false ),
'email_c_label' => array( 'type' => 'text',
'label' => array( 'text' => 'Email',
'type' => 0 ),
'editedByRte' => false ),
'grid_field4' => array( 'field' => 'email',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => false ),
'email_c_tooltip' => array( 'type' => 'text',
'label' => array( 'text' => '* Your email will be visible only to moderators',
'type' => 0 ),
'editedByRte' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'search_panel_field' => array( 'field' => 'status',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field1' => array( 'field' => 'images',
'type' => 'search_panel_field',
'required' => false ),
'logo' => array( 'eventId' => 'sgb_logo',
'label' => array( 'text' => 'sgb_logo',
'type' => 0 ),
'type' => 'snippet',
'customCSS' => ':host {
    text-shadow: 0 1px 0 rgb(0 0 0 / 10%);
    line-height: 20px;
    font-size: 18px;
}
' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'inline_add' => array( 'type' => 'inline_add' ),
'inline_save_all' => array( 'type' => 'inline_save_all' ),
'inline_cancel_all' => array( 'type' => 'inline_cancel_all' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'sgb_suggestions' => 'true' ) ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field1' ) ),
'menu' => array( 'type' => 'menu' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'admin_header' => array( 'type' => 'text',
'label' => array( 'text' => 'Board Admin Panel',
'type' => 0 ),
'editedByRte' => false ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'sgb_admin_notification' => array( 'type' => 'snippet',
'eventId' => 'sgb_admin_notification',
'label' => array( 'text' => 'sgb_admin_notification',
'type' => 0 ) ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'addToBottom' => true,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>