<?php
			$optionsArray = array( 'details' => array( 'sgb_comments' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'title',
'suggestion',
'categoryid',
'images',
'name',
'email' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'title' => array( 'integrated_edit_field7' ),
'suggestion' => array( 'integrated_edit_field4' ),
'categoryid' => array( 'integrated_edit_field6' ),
'images' => array( 'integrated_edit_field2' ),
'name' => array( 'integrated_edit_field' ),
'email' => array( 'integrated_edit_field1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'sgb_already_posted' ),
'below-grid' => array(  ),
'supertop' => array( 'logo',
'loginform_login',
'username_button' ),
'top' => array( 'sgb_promo' ),
'grid' => array( 'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field4',
'add_save',
'add_back_list',
'integrated_edit_field',
'integrated_edit_field2',
'integrated_edit_field1' ) ),
'formXtTags' => array( 'below-grid' => array(  ) ),
'itemForms' => array( 'sgb_already_posted' => 'above-grid',
'logo' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'sgb_promo' => 'top',
'integrated_edit_field7' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field4' => 'grid',
'add_save' => 'grid',
'add_back_list' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field1' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'add_save' => array( 'location' => 'grid',
'cellId' => 'c' ),
'add_back_list' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c6' ) ),
'itemVisiblity' => array( 'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'add_save' => array( 'add_save' ),
'add_back_list' => array( 'add_back_list' ),
'integrated_edit_field' => array( 'integrated_edit_field7',
'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field',
'integrated_edit_field1' ),
'edit_field' => array( 'integrated_edit_field2' ),
'logo' => array( 'logo' ),
'username_button' => array( 'username_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'snippet' => array( 'sgb_promo',
'sgb_already_posted' ),
'changepassword_link' => array( 'changepassword_link' ),
'loginform_login' => array( 'loginform_login' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ) ),
'width' => 2,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'sgb_already_posted' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ) ),
'c3' => array( 'model' => 'c3',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'sgb_promo' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 2 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 1 ),
array( 'cell' => 'c6' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field4' ),
'padding' => array( 'padding' => '20px' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
border-radius: 4px;
}
' ),
'c' => array( 'model' => 'c3',
'items' => array( 'add_save',
'add_back_list' ),
'padding' => array( 'padding' => '20px' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
border-radius: 4px;
}
',
'orientation' => 'horizontal',
'align' => 'right' ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ),
'padding' => array( 'padding' => '20px' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
border-radius: 4px;
}
' ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1' ),
'padding' => array( 'padding' => '20px' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
border-radius: 4px;
}
' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_save' => array( 'type' => 'add_save',
'label' => array( 'type' => 0,
'text' => 'Post Suggestion' ),
'icon' => array( 'glyph' => '' ) ),
'add_back_list' => array( 'type' => 'add_back_list',
'label' => array( 'type' => 0,
'text' => 'Cancel' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
 margin-right:15px;
}
' ),
'integrated_edit_field7' => array( 'field' => 'title',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'suggestion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'categoryid',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'categoryid',
'table' => 'sgb_suggestions',
'type' => 3 ) ),
'integrated_edit_field2' => array( 'field' => 'images',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'logo' => array( 'type' => 'logo' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'sgb_promo' => array( 'type' => 'snippet',
'eventId' => 'sgb_promo',
'label' => array( 'text' => 'sgb_promo',
'type' => 0 ) ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'integrated_edit_field' => array( 'field' => 'name',
'type' => 'integrated_edit_field',
'orientation' => 0,
'tooltip' => array( 'field' => 'name',
'table' => 'sgb_suggestions',
'type' => 4 ) ),
'integrated_edit_field1' => array( 'field' => 'email',
'type' => 'integrated_edit_field',
'orientation' => 0,
'tooltip' => array( 'field' => 'email',
'table' => 'sgb_suggestions',
'type' => 4 ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'sgb_already_posted' => array( 'type' => 'snippet',
'eventId' => 'sgb_suggestions_already_posted',
'label' => array( 'text' => 'sgb_already_posted',
'type' => 0 ) ) ),
'dbProps' => array(  ),
'version' => 11,
'pageAlign' => 'center',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>