<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_contributor  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowDashboard"]=true;

		$this->events["BeforeProcessDashboard"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowDashboard(&$xt, &$templatefile, $pageObject)
{

		$pageObject->AddCSSFile("styles/sgb.css");
$style = "contributor sgb ".postvalue("orderby");
if(Security::isLoggedIn()){
	$style.= " login ".Security::getUserGroup();
}
$xt->assign("stylename",$style);
;
} // function BeforeShowDashboard

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
				// Dashboard page: Before process
function BeforeProcessDashboard($pageObject)
{

		

if( postvalue("ipaction")!=false ){

	if(postvalue("ipaction") === "block"){
		$is_blocked_rs = DB::Select("sgb_blockedip",array("ip" => postvalue("ipaction")));
		$is_blocked = $is_blocked_rs->fetchAssoc();
		if(!$is_blocked)
			DB::Insert("sgb_blockedip",array("ip"=>postvalue("ip"),"blocked_date" => time() ) );
	}
	if(postvalue("ipaction") === "unblock")
		DB::Delete("sgb_blockedip",array("ip"=>postvalue("ip") ) );
	exit();

}

;
} // function BeforeProcessDashboard

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		


		// dashboatd snippets function
	function event_contributor_snippet( &$header, &$icon )
	{
		$_SESSION["autor"] = urldecode(postvalue("autor"));
$_SESSION["aname"] = urldecode(postvalue("aname"));
$header = "Contributor";
echo "<span class='cinfo'>";
echo "<p>Contributor name <b>".$_SESSION["aname"]."</b></p>";
echo "<p>Email :<b>".$_SESSION["autor"]."</b></p>";
echo "</span>";;
	}

}
?>