<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => true ),
'fields' => array( 'gridFields' => array( 'fullname',
'email',
'username',
'password' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'fullname' => array( 'integrated_edit_field',
'edit_field_label',
'edit_field_tooltip' ),
'email' => array( 'integrated_edit_field1',
'edit_field_label1',
'edit_field_tooltip1' ),
'username' => array( 'integrated_edit_field2',
'edit_field_label2',
'edit_field_tooltip2' ),
'password' => array( 'integrated_edit_field3' ),
'confirm_aoel3cx' => array( 'integrated_confirm_password' ) ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'register_message',
'step_nav' ),
'top' => array( 'register_header',
'register_logo1',
'text4' ),
'footer' => array( 'next_step',
'register_save',
'back_to_login',
'register_reset',
'text',
'text2',
'text1' ),
'grid' => array( 'edit_field_label',
'integrated_edit_field',
'edit_field_tooltip',
'captcha' ),
'step2' => array( 'edit_field_label1',
'integrated_edit_field1',
'edit_field_tooltip1',
'edit_field_label2',
'integrated_edit_field2',
'edit_field_tooltip2' ),
'step3' => array( 'integrated_edit_field3',
'integrated_confirm_password' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'register_message' => 'above-grid',
'step_nav' => 'above-grid',
'register_header' => 'top',
'register_logo1' => 'top',
'text4' => 'top',
'next_step' => 'footer',
'register_save' => 'footer',
'back_to_login' => 'footer',
'register_reset' => 'footer',
'text' => 'footer',
'text2' => 'footer',
'text1' => 'footer',
'edit_field_label' => 'grid',
'integrated_edit_field' => 'grid',
'edit_field_tooltip' => 'grid',
'captcha' => 'grid',
'edit_field_label1' => 'step2',
'integrated_edit_field1' => 'step2',
'edit_field_tooltip1' => 'step2',
'edit_field_label2' => 'step2',
'integrated_edit_field2' => 'step2',
'edit_field_tooltip2' => 'step2',
'integrated_edit_field3' => 'step3',
'integrated_confirm_password' => 'step3' ),
'itemLocations' => array( 'edit_field_label' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'edit_field_tooltip' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'captcha' => array( 'location' => 'grid',
'cellId' => 'c' ),
'edit_field_label1' => array( 'location' => 'step2',
'cellId' => 'c1' ),
'integrated_edit_field1' => array( 'location' => 'step2',
'cellId' => 'c1' ),
'edit_field_tooltip1' => array( 'location' => 'step2',
'cellId' => 'c1' ),
'edit_field_label2' => array( 'location' => 'step2',
'cellId' => 'c' ),
'integrated_edit_field2' => array( 'location' => 'step2',
'cellId' => 'c' ),
'edit_field_tooltip2' => array( 'location' => 'step2',
'cellId' => 'c' ),
'integrated_edit_field3' => array( 'location' => 'step3',
'cellId' => 'c1' ),
'integrated_confirm_password' => array( 'location' => 'step3',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'register_header' => array( 'register_header' ),
'register_reset' => array( 'register_reset' ),
'register_message' => array( 'register_message' ),
'register_save' => array( 'register_save' ),
'back_to_login' => array( 'back_to_login' ),
'edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2' ),
'integrated_edit_field' => array( 'integrated_edit_field3' ),
'integrated_confirm_password' => array( 'integrated_confirm_password' ),
'captcha' => array( 'captcha' ),
'next_step' => array( 'next_step' ),
'step_nav' => array( 'step_nav' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1',
'edit_field_label2' ),
'edit_field_tooltip' => array( 'edit_field_tooltip',
'edit_field_tooltip1',
'edit_field_tooltip2' ),
'text' => array( 'text',
'text1',
'text2',
'text4',
'register_logo1' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field_label',
'integrated_edit_field',
'edit_field_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'captcha' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'step2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field_label1',
'integrated_edit_field1',
'edit_field_tooltip1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'edit_field_label2',
'integrated_edit_field2',
'edit_field_tooltip2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'step3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3',
'integrated_confirm_password' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'page' => array( 'verticalBar' => false,
'multiStep' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'register' => array( 'gridFields' => array( 'fullname',
'email',
'username',
'password' ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'register',
'type' => 'register',
'layoutId' => 'pretty1',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'register-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'register_message' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'step_nav' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'register-header',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'register_header' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'register_logo1' ),
'align' => 'center' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'text4' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'register-below-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c6',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'next_step',
'register_save',
'back_to_login' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'register_reset' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'text' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'text2' ) ),
'c5' => array( 'model' => 'c2',
'items' => array(  ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'text1' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'edit_field_label',
'integrated_edit_field',
'edit_field_tooltip' ),
'align' => 'center' ),
'c' => array( 'model' => 'c3',
'items' => array( 'captcha' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'step2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c3',
'items' => array( 'edit_field_label1',
'integrated_edit_field1',
'edit_field_tooltip1' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'edit_field_label2',
'integrated_edit_field2',
'edit_field_tooltip2' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'step3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3',
'integrated_confirm_password' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'register_header' => array( 'type' => 'register_header' ),
'register_reset' => array( 'type' => 'register_reset' ),
'register_message' => array( 'type' => 'register_message' ),
'register_save' => array( 'type' => 'register_save' ),
'back_to_login' => array( 'type' => 'back_to_login',
'tooltip' => array( 'type' => 0,
'text' => 'If you already have an account you can login!' ),
'bold' => true,
'icon' => array( 'glyph' => 'log-in' ),
'buttonStyle' => 'success' ),
'integrated_edit_field' => array( 'field' => 'fullname',
'type' => 'edit_field',
'orientation' => 0,
'label' => array( 'field' => 'fullname',
'table' => 'public.hispmdusers',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'integrated_edit_field1' => array( 'field' => 'email',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field2' => array( 'field' => 'username',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field3' => array( 'field' => 'password',
'type' => 'integrated_edit_field',
'orientation' => 0,
'color' => '#00274c',
'bold' => true ),
'integrated_confirm_password' => array( 'type' => 'integrated_confirm_password',
'field' => 'confirm_aoel3cx',
'orientation' => 0,
'color' => '#00274c',
'bold' => true ),
'captcha' => array( 'type' => 'captcha' ),
'next_step' => array( 'type' => 'next_step' ),
'step_nav' => array( 'type' => 'step_nav' ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'fullname',
'separated' => true,
'bold' => true,
'color' => '#00274c' ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'fullname',
'separated' => true ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'email',
'separated' => true,
'bold' => true,
'color' => '#00274c' ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'email',
'separated' => true ),
'edit_field_label2' => array( 'type' => 'edit_field_label',
'field' => 'username',
'separated' => true,
'bold' => true,
'color' => '#00274c' ),
'edit_field_tooltip2' => array( 'type' => 'edit_field_tooltip',
'field' => 'username',
'separated' => true ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<br>
NOTE: This Application is for Internal Use only! It can only be accessed by an authorized personel!
<br>
',
'type' => 0 ),
'editedByRte' => false,
'bold' => true ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => '<br>
Please make sure to fill out all mandatory fields in all steps!
<br>',
'type' => 0 ),
'editedByRte' => false,
'italic' => true ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => '<br>',
'type' => 0 ),
'editedByRte' => false ),
'text4' => array( 'type' => 'text',
'label' => array( 'text' => 'Welcome To Health Information Systems Performance Monitoring Dashboard (HISPMD)',
'type' => 0 ),
'editedByRte' => false,
'color' => '#3a89db',
'bold' => true ),
'register_logo1' => array( 'type' => 'text',
'label' => array( 'text' => '<p><img src="moh_black.png" alt="Health Information System Performance Monitoring Dashboard (HISPMD)" width="147" height="47" class="mCS_img_loaded" /></p>',
'type' => 0 ),
'editedByRte' => false,
'font-size' => '24px' ) ),
'dbProps' => array(  ),
'steps' => array( array( 'location' => 'grid',
'label' => array( 'text' => 'Name & Designation',
'type' => 0 ) ),
array( 'location' => 'step2',
'label' => array( 'text' => 'Email & Username',
'type' => 0 ) ),
array( 'location' => 'step3',
'label' => array( 'text' => 'Set Password & Confirm',
'type' => 0 ) ) ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image',
'image' => array( 'image' => 'MOH_logo_text.png',
'source' => 2 ) ),
'imageBgColor' => '#f7fbff',
'controlsBgColor' => 'white',
'imagePosition' => 'left',
'pageCSS' => '/* Put  your custom CSS code here */
.r-pretty-login-page[data-image-shadow]:not([data-image-fullsize])>.r-sideimage>.r-image img
{
    box-shadow: 0 0 17px 7px #D7D7D7;
}' );
		?>