<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'rights_save',
'rights_reset',
'rights_displaying_tables',
'rights_ordering_tables',
'rights_add_group',
'rights_del_group',
'rights_rename_group',
'rights_copy_permissions',
'text' ),
'below-grid' => array(  ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'notifications',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array(  ),
'grid' => array( 'rights_search',
'rights_name_a',
'rights_name_e',
'rights_name_d',
'rights_name_s',
'rights_name_p',
'rights_name_i',
'rights_name_m',
'rights_name_m1',
'rights_checkbox_page',
'rights_page',
'rights_checkbox_page_a',
'rights_checkbox_page_e',
'rights_checkbox_page_d',
'rights_checkbox_page_s',
'rights_checkbox_page_p',
'rights_checkbox_page_i',
'rights_expand_all',
'rights_checkbox_all_a',
'rights_checkbox_all_e',
'rights_checkbox_all_d',
'rights_checkbox_all_s',
'rights_checkbox_all_p',
'rights_checkbox_all_i',
'rights_checkbox_all_m',
'rights_checkbox_table',
'rights_table',
'rights_show_pages',
'rights_hide_pages',
'rights_group_expander',
'rights_checkbox_a',
'rights_checkbox_e',
'rights_checkbox_d',
'rights_checkbox_s',
'rights_checkbox_p',
'rights_checkbox_i',
'rights_checkbox_m' ) ),
'formXtTags' => array( 'below-grid' => array(  ),
'top' => array(  ) ),
'itemForms' => array( 'rights_save' => 'above-grid',
'rights_reset' => 'above-grid',
'rights_displaying_tables' => 'above-grid',
'rights_ordering_tables' => 'above-grid',
'rights_add_group' => 'above-grid',
'rights_del_group' => 'above-grid',
'rights_rename_group' => 'above-grid',
'rights_copy_permissions' => 'above-grid',
'text' => 'above-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'notifications' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'rights_search' => 'grid',
'rights_name_a' => 'grid',
'rights_name_e' => 'grid',
'rights_name_d' => 'grid',
'rights_name_s' => 'grid',
'rights_name_p' => 'grid',
'rights_name_i' => 'grid',
'rights_name_m' => 'grid',
'rights_name_m1' => 'grid',
'rights_checkbox_page' => 'grid',
'rights_page' => 'grid',
'rights_checkbox_page_a' => 'grid',
'rights_checkbox_page_e' => 'grid',
'rights_checkbox_page_d' => 'grid',
'rights_checkbox_page_s' => 'grid',
'rights_checkbox_page_p' => 'grid',
'rights_checkbox_page_i' => 'grid',
'rights_expand_all' => 'grid',
'rights_checkbox_all_a' => 'grid',
'rights_checkbox_all_e' => 'grid',
'rights_checkbox_all_d' => 'grid',
'rights_checkbox_all_s' => 'grid',
'rights_checkbox_all_p' => 'grid',
'rights_checkbox_all_i' => 'grid',
'rights_checkbox_all_m' => 'grid',
'rights_checkbox_table' => 'grid',
'rights_table' => 'grid',
'rights_show_pages' => 'grid',
'rights_hide_pages' => 'grid',
'rights_group_expander' => 'grid',
'rights_checkbox_a' => 'grid',
'rights_checkbox_e' => 'grid',
'rights_checkbox_d' => 'grid',
'rights_checkbox_s' => 'grid',
'rights_checkbox_p' => 'grid',
'rights_checkbox_i' => 'grid',
'rights_checkbox_m' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'rights_save' => array( 'rights_save' ),
'rights_reset' => array( 'rights_reset' ),
'rights_displaying_tables' => array( 'rights_displaying_tables' ),
'rights_ordering_tables' => array( 'rights_ordering_tables' ),
'rights_add_group' => array( 'rights_add_group' ),
'rights_del_group' => array( 'rights_del_group' ),
'rights_rename_group' => array( 'rights_rename_group' ),
'rights_copy_permissions' => array( 'rights_copy_permissions' ),
'rights_search' => array( 'rights_search' ),
'rights_name_a' => array( 'rights_name_a' ),
'rights_name_e' => array( 'rights_name_e' ),
'rights_name_d' => array( 'rights_name_d' ),
'rights_name_s' => array( 'rights_name_s' ),
'rights_name_p' => array( 'rights_name_p' ),
'rights_name_i' => array( 'rights_name_i' ),
'rights_name_m' => array( 'rights_name_m' ),
'rights_name_m1' => array( 'rights_name_m1' ),
'rights_checkbox_page' => array( 'rights_checkbox_page' ),
'rights_page' => array( 'rights_page' ),
'rights_checkbox_page_a' => array( 'rights_checkbox_page_a' ),
'rights_checkbox_page_e' => array( 'rights_checkbox_page_e' ),
'rights_checkbox_page_d' => array( 'rights_checkbox_page_d' ),
'rights_checkbox_page_s' => array( 'rights_checkbox_page_s' ),
'rights_checkbox_page_p' => array( 'rights_checkbox_page_p' ),
'rights_checkbox_page_i' => array( 'rights_checkbox_page_i' ),
'rights_expand_all' => array( 'rights_expand_all' ),
'rights_checkbox_all_a' => array( 'rights_checkbox_all_a' ),
'rights_checkbox_all_e' => array( 'rights_checkbox_all_e' ),
'rights_checkbox_all_d' => array( 'rights_checkbox_all_d' ),
'rights_checkbox_all_s' => array( 'rights_checkbox_all_s' ),
'rights_checkbox_all_p' => array( 'rights_checkbox_all_p' ),
'rights_checkbox_all_i' => array( 'rights_checkbox_all_i' ),
'rights_checkbox_all_m' => array( 'rights_checkbox_all_m' ),
'rights_checkbox_table' => array( 'rights_checkbox_table' ),
'rights_table' => array( 'rights_table' ),
'rights_show_pages' => array( 'rights_show_pages' ),
'rights_hide_pages' => array( 'rights_hide_pages' ),
'rights_group_expander' => array( 'rights_group_expander' ),
'rights_checkbox_a' => array( 'rights_checkbox_a' ),
'rights_checkbox_e' => array( 'rights_checkbox_e' ),
'rights_checkbox_d' => array( 'rights_checkbox_d' ),
'rights_checkbox_s' => array( 'rights_checkbox_s' ),
'rights_checkbox_p' => array( 'rights_checkbox_p' ),
'rights_checkbox_i' => array( 'rights_checkbox_i' ),
'rights_checkbox_m' => array( 'rights_checkbox_m' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'exit_adminarea_link' => array( 'exit_adminarea_link' ),
'text' => array( 'text' ),
'changepassword_link' => array( 'changepassword_link' ),
'notifications' => array( 'notifications' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'admin_rights_list',
'type' => 'admin_rights_list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'admin-rights-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'rights_save',
'rights_reset' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'rights_displaying_tables',
'rights_ordering_tables' ) ),
'c4' => array( 'model' => 'c4',
'items' => array( 'rights_add_group',
'rights_del_group',
'rights_rename_group',
'rights_copy_permissions' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'text' ) ),
'c3' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'admin-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'admin-leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'notifications',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'admin-leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'admin-header',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'admin-rights-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'headcell_search' ),
array( 'cell' => 'headcell_a' ),
array( 'cell' => 'headcell_e' ),
array( 'cell' => 'headcell_d' ),
array( 'cell' => 'headcell_s' ),
array( 'cell' => 'headcell_p' ),
array( 'cell' => 'headcell_i' ),
array( 'cell' => 'headcell_m' ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'headcell_expand' ),
array( 'cell' => 'headcell_all_a' ),
array( 'cell' => 'headcell_all_e' ),
array( 'cell' => 'headcell_all_d' ),
array( 'cell' => 'headcell_all_s' ),
array( 'cell' => 'headcell_all_p' ),
array( 'cell' => 'headcell_all_i' ),
array( 'cell' => 'headcell_all_m' ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_table' ),
array( 'cell' => 'cell_a' ),
array( 'cell' => 'cell_e' ),
array( 'cell' => 'cell_d' ),
array( 'cell' => 'cell_s' ),
array( 'cell' => 'cell_p' ),
array( 'cell' => 'cell_i' ),
array( 'cell' => 'cell_m' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_page' ),
array( 'cell' => 'cell_page_a' ),
array( 'cell' => 'cell_page_e' ),
array( 'cell' => 'cell_page_d' ),
array( 'cell' => 'cell_page_s' ),
array( 'cell' => 'cell_page_p' ),
array( 'cell' => 'cell_page_i' ),
array( 'cell' => 'cell_page_m' ) ),
'section' => 'page' ) ),
'cells' => array( 'headcell_search' => array( 'model' => 'headcell_search',
'items' => array( 'rights_search' ) ),
'headcell_a' => array( 'model' => 'headcell_a',
'items' => array( 'rights_name_a' ) ),
'headcell_e' => array( 'model' => 'headcell_e',
'items' => array( 'rights_name_e' ) ),
'headcell_d' => array( 'model' => 'headcell_d',
'items' => array( 'rights_name_d' ) ),
'headcell_s' => array( 'model' => 'headcell_s',
'items' => array( 'rights_name_s' ) ),
'headcell_p' => array( 'model' => 'headcell_p',
'items' => array( 'rights_name_p' ) ),
'headcell_i' => array( 'model' => 'headcell_i',
'items' => array( 'rights_name_i' ) ),
'headcell_m' => array( 'model' => 'headcell_m',
'items' => array( 'rights_name_m',
'rights_name_m1' ) ),
'cell_page' => array( 'model' => 'cell_page',
'items' => array( 'rights_checkbox_page',
'rights_page' ) ),
'cell_page_a' => array( 'model' => 'cell_page_a',
'items' => array( 'rights_checkbox_page_a' ),
'permission' => 'A' ),
'cell_page_e' => array( 'model' => 'cell_page_e',
'items' => array( 'rights_checkbox_page_e' ),
'permission' => 'E' ),
'cell_page_d' => array( 'model' => 'cell_page_d',
'items' => array( 'rights_checkbox_page_d' ),
'permission' => 'D' ),
'cell_page_s' => array( 'model' => 'cell_page_s',
'items' => array( 'rights_checkbox_page_s' ),
'permission' => 'S' ),
'cell_page_p' => array( 'model' => 'cell_page_p',
'items' => array( 'rights_checkbox_page_p' ),
'permission' => 'P' ),
'cell_page_i' => array( 'model' => 'cell_page_i',
'items' => array( 'rights_checkbox_page_i' ),
'permission' => 'I' ),
'cell_page_m' => array( 'model' => 'cell_page_m',
'items' => array(  ) ),
'headcell_expand' => array( 'model' => 'headcell_expand',
'items' => array( 'rights_expand_all' ) ),
'headcell_all_a' => array( 'model' => 'headcell_all_a',
'items' => array( 'rights_checkbox_all_a' ),
'permission' => 'A' ),
'headcell_all_e' => array( 'model' => 'headcell_all_e',
'items' => array( 'rights_checkbox_all_e' ),
'permission' => 'E' ),
'headcell_all_d' => array( 'model' => 'headcell_all_d',
'items' => array( 'rights_checkbox_all_d' ),
'permission' => 'D' ),
'headcell_all_s' => array( 'model' => 'headcell_all_s',
'items' => array( 'rights_checkbox_all_s' ),
'permission' => 'S' ),
'headcell_all_p' => array( 'model' => 'headcell_all_p',
'items' => array( 'rights_checkbox_all_p' ),
'permission' => 'P' ),
'headcell_all_i' => array( 'model' => 'headcell_all_i',
'items' => array( 'rights_checkbox_all_i' ),
'permission' => 'I' ),
'headcell_all_m' => array( 'model' => 'headcell_all_m',
'items' => array( 'rights_checkbox_all_m' ),
'permission' => 'M' ),
'cell_table' => array( 'model' => 'cell_table',
'items' => array( 'rights_checkbox_table',
'rights_table',
'rights_show_pages',
'rights_hide_pages',
'rights_group_expander' ) ),
'cell_a' => array( 'model' => 'cell_a',
'items' => array( 'rights_checkbox_a' ),
'permission' => 'A' ),
'cell_e' => array( 'model' => 'cell_e',
'items' => array( 'rights_checkbox_e' ),
'permission' => 'E' ),
'cell_d' => array( 'model' => 'cell_d',
'items' => array( 'rights_checkbox_d' ),
'permission' => 'D' ),
'cell_s' => array( 'model' => 'cell_s',
'items' => array( 'rights_checkbox_s' ),
'permission' => 'S' ),
'cell_p' => array( 'model' => 'cell_p',
'items' => array( 'rights_checkbox_p' ),
'permission' => 'P' ),
'cell_i' => array( 'model' => 'cell_i',
'items' => array( 'rights_checkbox_i' ),
'permission' => 'I' ),
'cell_m' => array( 'model' => 'cell_m',
'items' => array( 'rights_checkbox_m' ),
'permission' => 'M' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'rights_save' => array( 'type' => 'rights_save' ),
'rights_reset' => array( 'type' => 'rights_reset' ),
'rights_displaying_tables' => array( 'type' => 'rights_displaying_tables' ),
'rights_ordering_tables' => array( 'type' => 'rights_ordering_tables' ),
'rights_add_group' => array( 'type' => 'rights_add_group' ),
'rights_del_group' => array( 'type' => 'rights_del_group' ),
'rights_rename_group' => array( 'type' => 'rights_rename_group' ),
'rights_copy_permissions' => array( 'type' => 'rights_copy_permissions' ),
'rights_search' => array( 'type' => 'rights_search' ),
'rights_name_a' => array( 'type' => 'rights_name_a' ),
'rights_name_e' => array( 'type' => 'rights_name_e' ),
'rights_name_d' => array( 'type' => 'rights_name_d' ),
'rights_name_s' => array( 'type' => 'rights_name_s' ),
'rights_name_p' => array( 'type' => 'rights_name_p' ),
'rights_name_i' => array( 'type' => 'rights_name_i' ),
'rights_name_m' => array( 'type' => 'rights_name_m' ),
'rights_name_m1' => array( 'type' => 'rights_name_m1' ),
'rights_checkbox_page' => array( 'type' => 'rights_checkbox_page' ),
'rights_page' => array( 'type' => 'rights_page' ),
'rights_checkbox_page_a' => array( 'type' => 'rights_checkbox_page_a' ),
'rights_checkbox_page_e' => array( 'type' => 'rights_checkbox_page_e' ),
'rights_checkbox_page_d' => array( 'type' => 'rights_checkbox_page_d' ),
'rights_checkbox_page_s' => array( 'type' => 'rights_checkbox_page_s' ),
'rights_checkbox_page_p' => array( 'type' => 'rights_checkbox_page_p' ),
'rights_checkbox_page_i' => array( 'type' => 'rights_checkbox_page_i' ),
'rights_expand_all' => array( 'type' => 'rights_expand_all' ),
'rights_checkbox_all_a' => array( 'type' => 'rights_checkbox_all_a' ),
'rights_checkbox_all_e' => array( 'type' => 'rights_checkbox_all_e' ),
'rights_checkbox_all_d' => array( 'type' => 'rights_checkbox_all_d' ),
'rights_checkbox_all_s' => array( 'type' => 'rights_checkbox_all_s' ),
'rights_checkbox_all_p' => array( 'type' => 'rights_checkbox_all_p' ),
'rights_checkbox_all_i' => array( 'type' => 'rights_checkbox_all_i' ),
'rights_checkbox_all_m' => array( 'type' => 'rights_checkbox_all_m' ),
'rights_checkbox_table' => array( 'type' => 'rights_checkbox_table' ),
'rights_table' => array( 'type' => 'rights_table' ),
'rights_show_pages' => array( 'type' => 'rights_show_pages' ),
'rights_hide_pages' => array( 'type' => 'rights_hide_pages' ),
'rights_group_expander' => array( 'type' => 'rights_group_expander' ),
'rights_checkbox_a' => array( 'type' => 'rights_checkbox_a' ),
'rights_checkbox_e' => array( 'type' => 'rights_checkbox_e' ),
'rights_checkbox_d' => array( 'type' => 'rights_checkbox_d' ),
'rights_checkbox_s' => array( 'type' => 'rights_checkbox_s' ),
'rights_checkbox_p' => array( 'type' => 'rights_checkbox_p' ),
'rights_checkbox_i' => array( 'type' => 'rights_checkbox_i' ),
'rights_checkbox_m' => array( 'type' => 'rights_checkbox_m' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'main' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'exit_adminarea_link',
'changepassword_link' ) ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'exit_adminarea_link' => array( 'type' => 'exit_adminarea_link' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<br>',
'type' => 0 ),
'editedByRte' => false ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'notifications' => array( 'type' => 'notifications' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>