<?php
			$optionsArray = array( 'welcome' => array( 'welcomePageSkip' => true,
'welcomeItems' => array( 'text5' => array( 'menutItem' => false ),
'welcome_item15' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => '{04AFFBE6-86C0-47b0-ADD3-BA7FA19CA6FC}',
'page' => null ),
'welcome_item31' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'AI_Data_Assistant',
'page' => 'list' ),
'expand_menu_button' => array( 'menutItem' => false ),
'collapse_button' => array( 'menutItem' => false ),
'text1' => array( 'menutItem' => false ),
'text' => array( 'menutItem' => false ),
'logo' => array( 'menutItem' => false ),
'expand_button' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'text4' => array( 'menutItem' => false ),
'welcome_group' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DataQuality',
'page' => 'list' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DataUse',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DigitalHealth',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DigitalHealthApps',
'page' => 'list' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'FinancialResources',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'HISGovernance',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'HISPartners',
'page' => 'list' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'HealthFacilities',
'page' => 'list' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'HealthUnits',
'page' => 'list' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Publications',
'page' => 'list' ),
'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Regions',
'page' => 'list' ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Workforce',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Research',
'page' => 'list' ) ) ),
'text3' => array( 'menutItem' => false ),
'welcome_group1' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item21' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Dashboard_Reports',
'page' => 'list' ),
'welcome_item22' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Operational_Status',
'page' => 'list' ),
'welcome_item23' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Region',
'page' => 'list' ),
'welcome_item24' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Zone',
'page' => 'list' ),
'welcome_item25' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Woreda',
'page' => 'list' ) ) ),
'welcome_group2' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item27' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_AIO_Dashboard',
'page' => 'dashboard' ),
'welcome_item14' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Dashboard_Reports_Chart',
'page' => 'chart' ),
'welcome_item26' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Operational_Status_Chart',
'page' => 'chart' ),
'welcome_item28' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Region_Chart',
'page' => 'chart' ),
'welcome_item29' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Zone_Chart',
'page' => 'chart' ),
'welcome_item30' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Woreda_Chart',
'page' => 'chart' ) ) ),
'welcome_group3' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Dashboard_Report',
'page' => 'list' ),
'welcome_item16' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Status_Report',
'page' => 'list' ),
'welcome_item17' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Region_Report',
'page' => 'list' ),
'welcome_item19' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Zone_Report',
'page' => 'list' ),
'welcome_item20' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Woreda_Report',
'page' => 'list' ),
'welcome_item18' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Facilities',
'page' => 'list' ) ) ),
'text2' => array( 'menutItem' => false ),
'welcome_group4' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item34' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Analytics',
'page' => 'list' ),
'welcome_item38' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Analytics Chart',
'page' => 'chart' ),
'welcome_item39' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Analytics Report',
'page' => 'report' ),
'welcome_item36' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Indicator',
'page' => 'list' ),
'welcome_item37' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Organisation_Unit',
'page' => 'list' ),
'welcome_item42' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Periods',
'page' => 'list' ) ) ),
'welcome_group5' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item35' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Reporting_Rate',
'page' => 'list' ),
'welcome_item44' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Reporting_Rate_Report',
'page' => 'report' ),
'welcome_item43' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Reporting_Rate_Chart',
'page' => 'chart' ),
'welcome_item45' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Reporting_Rates_Chart',
'page' => 'chart' ),
'welcome_item41' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Datasets',
'page' => 'list' ),
'welcome_item40' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Reports',
'page' => 'list' ) ) ),
'text6' => array( 'menutItem' => false ),
'welcome_item33' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Organisation_Units',
'page' => 'list' ),
'welcome_item32' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DHIS2_Indicators',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'welcome_item15',
'welcome_item31',
'text5' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'text1',
'text' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'grid' => array( 'welcome_group',
'welcome_group1',
'text2',
'welcome_item33',
'welcome_item32',
'welcome_group3',
'welcome_group2',
'welcome_group5',
'welcome_group4',
'text3',
'text4',
'text6' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'welcome_item15' => 'above-grid',
'welcome_item31' => 'above-grid',
'text5' => 'above-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'text1' => 'supertop',
'text' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'welcome_group' => 'grid',
'welcome_group1' => 'grid',
'text2' => 'grid',
'welcome_item33' => 'grid',
'welcome_item32' => 'grid',
'welcome_group3' => 'grid',
'welcome_group2' => 'grid',
'welcome_group5' => 'grid',
'welcome_group4' => 'grid',
'text3' => 'grid',
'text4' => 'grid',
'text6' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'welcome_item' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item15',
'welcome_item16',
'welcome_item18',
'welcome_item17',
'welcome_item19',
'welcome_item20',
'welcome_item14',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item26',
'welcome_item27',
'welcome_item28',
'welcome_item29',
'welcome_item30',
'welcome_item31',
'welcome_item32',
'welcome_item33',
'welcome_item34',
'welcome_item36',
'welcome_item37',
'welcome_item38',
'welcome_item39',
'welcome_item40',
'welcome_item41',
'welcome_item42',
'welcome_item35',
'welcome_item43',
'welcome_item44',
'welcome_item45' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'welcome_group' => array( 'welcome_group',
'welcome_group1',
'welcome_group2',
'welcome_group3',
'welcome_group4',
'welcome_group5' ),
'text' => array( 'text',
'text1',
'text2',
'text3',
'text4',
'text5',
'text6' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'welcome_item15' ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'welcome_item31' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'text5' ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'menu-topbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'text1' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'text' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c16' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c17' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c14' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c15' ) ) ),
array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ) ) ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c18' ) ) ),
array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c7' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_group' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'welcome_group1' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'text2' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'welcome_item33',
'welcome_item32' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'welcome_group3' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'welcome_group2' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'welcome_group5' ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c9' => array( 'model' => 'c1',
'items' => array(  ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'welcome_group4' ) ),
'c11' => array( 'model' => 'c1',
'items' => array(  ) ),
'c12' => array( 'model' => 'c1',
'items' => array(  ) ),
'c13' => array( 'model' => 'c1',
'items' => array(  ) ),
'c14' => array( 'model' => 'c1',
'items' => array(  ) ),
'c15' => array( 'model' => 'c1',
'items' => array( 'text3' ) ),
'c16' => array( 'model' => 'c1',
'items' => array(  ) ),
'c17' => array( 'model' => 'c1',
'items' => array( 'text4' ) ),
'c18' => array( 'model' => 'c1',
'items' => array( 'text6' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DataQuality',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DataQuality',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'tree-conifer' ),
'linkComments' => array( 'text' => 'Data Quality description',
'type' => 0 ),
'background' => '#8FBC8B',
'linkType' => 0 ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DataUse',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DataUse',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'fire' ),
'linkComments' => array( 'text' => 'Data Use description',
'type' => 0 ),
'background' => '#6B8E23',
'linkType' => 0 ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DigitalHealth',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DigitalHealth',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'hand-right' ),
'linkComments' => array( 'text' => 'Digital Health description',
'type' => 0 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DigitalHealthApps',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DigitalHealthApps',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'leaf' ),
'linkComments' => array( 'text' => 'Digital Health Apps description',
'type' => 0 ),
'background' => '#CD5C5C',
'linkType' => 0 ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'FinancialResources',
'linkPage' => 'list',
'linkText' => array( 'table' => 'FinancialResources',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'shopping-cart' ),
'linkComments' => array( 'text' => 'Financial Resources description',
'type' => 0 ),
'background' => '#5F9EA0',
'linkType' => 0 ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'HISGovernance',
'linkPage' => 'list',
'linkText' => array( 'table' => 'HISGovernance',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'calendar' ),
'background' => '#7B68EE',
'linkType' => 0 ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'HISPartners',
'linkPage' => 'list',
'linkText' => array( 'table' => 'HISPartners',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'camera' ),
'background' => '#778899',
'linkType' => 0 ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'HealthFacilities',
'linkPage' => 'list',
'linkText' => array( 'table' => 'HealthFacilities',
'type' => 6 ),
'background' => '#3CB371',
'linkType' => 0 ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'HealthUnits',
'linkPage' => 'list',
'linkText' => array( 'table' => 'HealthUnits',
'type' => 6 ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Publications',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Publications',
'type' => 6 ),
'background' => '#4169E1',
'linkType' => 0 ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Regions',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Regions',
'type' => 6 ),
'background' => '#8FBC8B',
'linkType' => 0 ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Research',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Research',
'type' => 6 ),
'background' => '#DB7093',
'linkType' => 0 ),
'welcome_item12' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Workforce',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Workforce',
'type' => 6 ),
'background' => '#CFAE83',
'linkType' => 0 ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Dashboard_Report',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Dashboard_Report',
'type' => 6 ),
'background' => '#6B8E23',
'linkType' => 0 ),
'welcome_item15' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => '{04AFFBE6-86C0-47b0-ADD3-BA7FA19CA6FC}',
'linkPage' => null,
'linkText' => null,
'linkType' => 0 ),
'welcome_item16' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Status_Report',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Status_Report',
'type' => 6 ),
'background' => '#EDCA00',
'linkType' => 0 ),
'welcome_item18' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Facilities',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Facilities',
'type' => 6 ),
'background' => '#9ACD32',
'linkType' => 0 ),
'welcome_item17' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Region_Report',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Region_Report',
'type' => 6 ),
'background' => '#1E90FF',
'linkType' => 0 ),
'welcome_item19' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Zone_Report',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Zone_Report',
'type' => 6 ),
'background' => '#6DA5C8',
'linkType' => 0 ),
'welcome_item20' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Woreda_Report',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Woreda_Report',
'type' => 6 ),
'background' => '#E07878',
'linkType' => 0 ),
'welcome_item14' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Dashboard_Reports_Chart',
'linkPage' => 'chart',
'linkText' => array( 'table' => 'MFR_Dashboard_Reports_Chart',
'type' => 6 ),
'background' => '#6DA5C8',
'linkType' => 0 ),
'welcome_item21' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Dashboard_Reports',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Dashboard_Reports',
'type' => 6 ),
'background' => '#5F9EA0',
'linkType' => 0 ),
'welcome_item22' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Operational_Status',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Operational_Status',
'type' => 6 ),
'background' => '#5F9EA0',
'linkType' => 0 ),
'welcome_item23' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Region',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Region',
'type' => 6 ),
'background' => '#CFAE83',
'linkType' => 0 ),
'welcome_item24' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Zone',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Zone',
'type' => 6 ),
'background' => '#CD5C5C',
'linkType' => 0 ),
'welcome_item25' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Woreda',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Woreda',
'type' => 6 ),
'background' => '#008B8B',
'linkType' => 0 ),
'welcome_item26' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Operational_Status_Chart',
'linkPage' => 'chart',
'linkText' => array( 'table' => 'MFR_Operational_Status_Chart',
'type' => 6 ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item27' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_AIO_Dashboard',
'linkPage' => 'dashboard',
'linkText' => array( 'table' => 'MFR_AIO_Dashboard',
'type' => 6 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item28' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Region_Chart',
'linkPage' => 'chart',
'linkText' => array( 'table' => 'MFR_Region_Chart',
'type' => 6 ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item29' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Zone_Chart',
'linkPage' => 'chart',
'linkText' => array( 'table' => 'MFR_Zone_Chart',
'type' => 6 ),
'background' => '#4169E1',
'linkType' => 0 ),
'welcome_item30' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Woreda_Chart',
'linkPage' => 'chart',
'linkText' => array( 'table' => 'MFR_Woreda_Chart',
'type' => 6 ),
'background' => '#1E90FF',
'linkType' => 0 ),
'welcome_group' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'HISPMD Indicators' ),
'items' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item12',
'welcome_item11' ) ),
'welcome_group1' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'Master Facility Registry: MFR' ),
'items' => array( 'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25' ) ),
'welcome_group2' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'Master Facility Registry: MFR CHARTS' ),
'items' => array( 'welcome_item27',
'welcome_item14',
'welcome_item26',
'welcome_item28',
'welcome_item29',
'welcome_item30' ) ),
'welcome_group3' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'MFR Data Update Setting' ),
'items' => array( 'welcome_item13',
'welcome_item16',
'welcome_item17',
'welcome_item19',
'welcome_item20',
'welcome_item18' ) ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'Health Information Systems Performance Monitoring Dashboard',
'type' => 0 ),
'editedByRte' => false,
'bold' => true ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => '<p><img src="./moh_white.png" alt="Health Information System Performance Monitoring Dashboard (HISPMD)" width="100%" height="30" class="mCS_img_loaded" /></p>',
'type' => 0 ),
'editedByRte' => false ),
'welcome_item31' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'AI_Data_Assistant',
'linkPage' => 'list',
'linkText' => array( 'table' => 'AI_Data_Assistant',
'type' => 6 ),
'background' => '#D2691E',
'linkType' => 0 ),
'welcome_item32' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Indicators',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DHIS2_Indicators',
'type' => 6 ),
'background' => '#008B8B',
'linkType' => 0 ),
'welcome_item33' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Organisation_Units',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DHIS2_Organisation_Units',
'type' => 6 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item34' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Analytics',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DHIS2_Analytics',
'type' => 6 ),
'background' => '#6DA5C8',
'linkType' => 0 ),
'welcome_item36' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Indicator',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DHIS2_Indicator',
'type' => 6 ),
'background' => '#8FBC8B',
'linkType' => 0 ),
'welcome_item37' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Organisation_Unit',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DHIS2_Organisation_Unit',
'type' => 6 ),
'background' => '#1E90FF',
'linkType' => 0 ),
'welcome_group4' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'DHIS2 Analytics' ),
'items' => array( 'welcome_item34',
'welcome_item38',
'welcome_item39',
'welcome_item36',
'welcome_item37',
'welcome_item42' ) ),
'welcome_item38' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Analytics Chart',
'linkPage' => 'chart',
'linkText' => array( 'table' => 'DHIS2_Analytics Chart',
'type' => 6 ),
'background' => '#4682B4',
'linkType' => 0 ),
'welcome_item39' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Analytics Report',
'linkPage' => 'report',
'linkText' => array( 'table' => 'DHIS2_Analytics Report',
'type' => 6 ),
'background' => '#00C2C5',
'linkType' => 0 ),
'welcome_item40' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Reports',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DHIS2_Reports',
'type' => 6 ),
'background' => '#D2AF80',
'linkType' => 0 ),
'welcome_item41' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Datasets',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DHIS2_Datasets',
'type' => 6 ),
'background' => '#CD5C5C',
'linkType' => 0 ),
'welcome_item42' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Periods',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DHIS2_Periods',
'type' => 6 ),
'background' => '#B22222',
'linkType' => 0 ),
'welcome_item35' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Reporting_Rate',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DHIS2_Reporting_Rate',
'type' => 6 ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item43' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Reporting_Rate_Chart',
'linkPage' => 'chart',
'linkText' => array( 'table' => 'DHIS2_Reporting_Rate_Chart',
'type' => 6 ),
'background' => '#6DA5C8',
'linkType' => 0 ),
'welcome_item44' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Reporting_Rate_Report',
'linkPage' => 'report',
'linkText' => array( 'table' => 'DHIS2_Reporting_Rate_Report',
'type' => 6 ),
'background' => '#1E90FF',
'linkType' => 0 ),
'welcome_item45' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DHIS2_Reporting_Rates_Chart',
'linkPage' => 'chart',
'linkText' => array( 'table' => 'DHIS2_Reporting_Rates_Chart',
'type' => 6 ),
'background' => '#DB7093',
'linkType' => 0 ),
'welcome_group5' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'DHIS2 Reporting Rates' ),
'items' => array( 'welcome_item35',
'welcome_item44',
'welcome_item43',
'welcome_item45',
'welcome_item41',
'welcome_item40' ) ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => '<p><strong>DHIS2</strong></p>',
'type' => 0 ),
'editedByRte' => true ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => '<p><strong>MFR</strong></p>',
'type' => 0 ),
'editedByRte' => true ),
'text4' => array( 'type' => 'text',
'label' => array( 'text' => '<p><strong>INDICATORS</strong></p>',
'type' => 0 ),
'editedByRte' => true ),
'text5' => array( 'type' => 'text',
'label' => array( 'type' => 0,
'text' => '<br><br><h2><strong>MENU</strong></h2>' ),
'editedByRte' => true ),
'text6' => array( 'type' => 'text',
'label' => array( 'text' => '<p><strong><em>NEW MENU</em></strong></p>',
'type' => 0 ),
'editedByRte' => true ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>