<?php
			$optionsArray = array( 'welcome' => array( 'welcomePageSkip' => true,
'welcomeItems' => array( 'expand_menu_button' => array( 'menutItem' => false ),
'collapse_button' => array( 'menutItem' => false ),
'logo' => array( 'menutItem' => false ),
'expand_button' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DataQuality',
'page' => 'list' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DataUse',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DigitalHealth',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'DigitalHealthApps',
'page' => 'list' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'FinancialResources',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'HISGovernance',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'HISPartners',
'page' => 'list' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'HealthFacilities',
'page' => 'list' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'HealthUnits',
'page' => 'list' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Publications',
'page' => 'list' ),
'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Regions',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Research',
'page' => 'list' ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Workforce',
'page' => 'list' ),
'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_REPORTING_REST_View',
'page' => 'list' ),
'welcome_item14' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Reporting',
'page' => 'list' ),
'welcome_item15' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => '{04AFFBE6-86C0-47b0-ADD3-BA7FA19CA6FC}',
'page' => null ),
'welcome_item16' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Status_Reporting',
'page' => 'list' ),
'welcome_item18' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'MFR_Facilities',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'supertop' => array( 'expand_menu_button',
'collapse_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'grid' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item18' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'welcome_item' => 'grid',
'welcome_item1' => 'grid',
'welcome_item2' => 'grid',
'welcome_item3' => 'grid',
'welcome_item4' => 'grid',
'welcome_item5' => 'grid',
'welcome_item6' => 'grid',
'welcome_item7' => 'grid',
'welcome_item8' => 'grid',
'welcome_item9' => 'grid',
'welcome_item10' => 'grid',
'welcome_item11' => 'grid',
'welcome_item12' => 'grid',
'welcome_item13' => 'grid',
'welcome_item14' => 'grid',
'welcome_item15' => 'grid',
'welcome_item16' => 'grid',
'welcome_item18' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'welcome_item' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item18' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'menu-topbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item18' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DataQuality',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DataQuality',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'tree-conifer' ),
'linkComments' => array( 'text' => 'Data Quality description',
'type' => 0 ),
'background' => '#8FBC8B',
'linkType' => 0 ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DataUse',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DataUse',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'fire' ),
'linkComments' => array( 'text' => 'Data Use description',
'type' => 0 ),
'background' => '#6B8E23',
'linkType' => 0 ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DigitalHealth',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DigitalHealth',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'hand-right' ),
'linkComments' => array( 'text' => 'Digital Health description',
'type' => 0 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'DigitalHealthApps',
'linkPage' => 'list',
'linkText' => array( 'table' => 'DigitalHealthApps',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'leaf' ),
'linkComments' => array( 'text' => 'Digital Health Apps description',
'type' => 0 ),
'background' => '#CD5C5C',
'linkType' => 0 ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'FinancialResources',
'linkPage' => 'list',
'linkText' => array( 'table' => 'FinancialResources',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'shopping-cart' ),
'linkComments' => array( 'text' => 'Financial Resources description',
'type' => 0 ),
'background' => '#5F9EA0',
'linkType' => 0 ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'HISGovernance',
'linkPage' => 'list',
'linkText' => array( 'table' => 'HISGovernance',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'calendar' ),
'background' => '#7B68EE',
'linkType' => 0 ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'HISPartners',
'linkPage' => 'list',
'linkText' => array( 'table' => 'HISPartners',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'camera' ),
'background' => '#778899',
'linkType' => 0 ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'HealthFacilities',
'linkPage' => 'list',
'linkText' => array( 'table' => 'HealthFacilities',
'type' => 6 ),
'background' => '#3CB371',
'linkType' => 0 ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'HealthUnits',
'linkPage' => 'list',
'linkText' => array( 'table' => 'HealthUnits',
'type' => 6 ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Publications',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Publications',
'type' => 6 ),
'background' => '#4169E1',
'linkType' => 0 ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Regions',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Regions',
'type' => 6 ),
'background' => '#8FBC8B',
'linkType' => 0 ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Research',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Research',
'type' => 6 ),
'background' => '#DB7093',
'linkType' => 0 ),
'welcome_item12' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Workforce',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Workforce',
'type' => 6 ),
'background' => '#CFAE83',
'linkType' => 0 ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_REPORTING_REST_View',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_REPORTING_REST_View',
'type' => 6 ),
'background' => '#6B8E23',
'linkType' => 0 ),
'welcome_item14' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Reporting',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Reporting',
'type' => 6 ),
'background' => '#DB7093',
'linkType' => 0 ),
'welcome_item15' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => '{04AFFBE6-86C0-47b0-ADD3-BA7FA19CA6FC}',
'linkPage' => null,
'linkText' => null,
'linkType' => 0 ),
'welcome_item16' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Status_Reporting',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Status_Reporting',
'type' => 6 ),
'background' => '#EDCA00',
'linkType' => 0 ),
'welcome_item18' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'MFR_Facilities',
'linkPage' => 'list',
'linkText' => array( 'table' => 'MFR_Facilities',
'type' => 6 ),
'background' => '#9ACD32',
'linkType' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>