<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'username',
'fullname',
'email',
'userpic',
'first_name',
'middle_name',
'last_name',
'phone_number',
'organisation_name',
'department',
'designation',
'apikey',
'ext_security_id' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'username' => array( 'integrated_edit_field' ),
'fullname' => array( 'integrated_edit_field1' ),
'email' => array( 'integrated_edit_field2' ),
'userpic' => array( 'integrated_edit_field3',
'edit_field_label',
'edit_field_tooltip' ),
'first_name' => array( 'integrated_edit_field4' ),
'middle_name' => array( 'integrated_edit_field5' ),
'last_name' => array( 'integrated_edit_field6' ),
'phone_number' => array( 'integrated_edit_field7' ),
'organisation_name' => array( 'integrated_edit_field8' ),
'department' => array( 'integrated_edit_field9' ),
'designation' => array( 'integrated_edit_field10' ),
'apikey' => array( 'integrated_edit_field11' ),
'ext_security_id' => array( 'integrated_edit_field12' ) ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'text3',
'integrated_edit_field10',
'edit_field_label',
'integrated_edit_field3',
'edit_field_tooltip',
'integrated_edit_field1',
'text1',
'integrated_edit_field',
'user_fields_title' ),
'below-grid' => array(  ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'notifications',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array(  ),
'grid' => array( 'fields_message',
'user_fields_reset',
'user_fields_save',
'tabs1',
'text2',
'text4',
'tabs',
'text' ),
'section' => array( 'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6' ),
'section1' => array( 'integrated_edit_field2',
'integrated_edit_field7' ),
'section2' => array( 'integrated_edit_field8',
'integrated_edit_field9' ),
'section3' => array( 'changepassword_link' ),
'section5' => array( 'twofactor_setup_comment',
'twofactor_settings',
'twofactor_label',
'twofactor_comment' ),
'section6' => array( 'integrated_edit_field11',
'integrated_edit_field12' ) ),
'formXtTags' => array( 'below-grid' => array(  ),
'top' => array(  ) ),
'itemForms' => array( 'text3' => 'above-grid',
'integrated_edit_field10' => 'above-grid',
'edit_field_label' => 'above-grid',
'integrated_edit_field3' => 'above-grid',
'edit_field_tooltip' => 'above-grid',
'integrated_edit_field1' => 'above-grid',
'text1' => 'above-grid',
'integrated_edit_field' => 'above-grid',
'user_fields_title' => 'above-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'fields_message' => 'grid',
'user_fields_reset' => 'grid',
'user_fields_save' => 'grid',
'tabs1' => 'grid',
'text2' => 'grid',
'text4' => 'grid',
'tabs' => 'grid',
'text' => 'grid',
'integrated_edit_field4' => 'section',
'integrated_edit_field5' => 'section',
'integrated_edit_field6' => 'section',
'integrated_edit_field2' => 'section1',
'integrated_edit_field7' => 'section1',
'integrated_edit_field8' => 'section2',
'integrated_edit_field9' => 'section2',
'changepassword_link' => 'section3',
'twofactor_setup_comment' => 'section5',
'twofactor_settings' => 'section5',
'twofactor_label' => 'section5',
'twofactor_comment' => 'section5',
'integrated_edit_field11' => 'section6',
'integrated_edit_field12' => 'section6' ),
'itemLocations' => array( 'fields_message' => array( 'location' => 'grid',
'cellId' => 'fields_message' ),
'user_fields_reset' => array( 'location' => 'grid',
'cellId' => 'buttons' ),
'user_fields_save' => array( 'location' => 'grid',
'cellId' => 'buttons' ),
'tabs1' => array( 'location' => 'grid',
'cellId' => '2factor_label1' ),
'text2' => array( 'location' => 'grid',
'cellId' => '2factor_label2' ),
'text4' => array( 'location' => 'grid',
'cellId' => '2factor_label3' ),
'tabs' => array( 'location' => 'grid',
'cellId' => '2factor_label4' ),
'text' => array( 'location' => 'grid',
'cellId' => '2factor_label' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field6' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field2' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field8' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section2',
'cellId' => 'c' ),
'changepassword_link' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'twofactor_setup_comment' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'twofactor_settings' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'twofactor_label' => array( 'location' => 'section5',
'cellId' => 'c' ),
'twofactor_comment' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field11' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field12' => array( 'location' => 'section6',
'cellId' => 'c2' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'fields_message' => array( 'fields_message' ),
'user_fields_reset' => array( 'user_fields_reset' ),
'user_fields_save' => array( 'user_fields_save' ),
'user_fields_title' => array( 'user_fields_title' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12' ),
'edit_field' => array( 'integrated_edit_field3' ),
'adminarea_link' => array( 'adminarea_link' ),
'text' => array( 'text',
'text1',
'text2',
'text3',
'text4' ),
'changepassword_link' => array( 'changepassword_link' ),
'notifications' => array( 'notifications' ),
'edit_field_label' => array( 'edit_field_label' ),
'edit_field_tooltip' => array( 'edit_field_tooltip' ),
'tabs' => array( 'tabs',
'tabs1' ),
'twofactor_settings' => array( 'twofactor_settings' ),
'twofactor_comment' => array( 'twofactor_comment' ),
'twofactor_setup_comment' => array( 'twofactor_setup_comment' ),
'twofactor_label' => array( 'twofactor_label' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( '2factor_label' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'2factor_label2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'2factor_label3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'text4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'2factor_label4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'2factor_label1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'tabs1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'2factor' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'fields_message3' => array( 'cols' => array( 0,
1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'fields_message' => array( 'cols' => array( 0,
1 ),
'rows' => array( 5 ),
'tags' => array( 'message_block' ),
'items' => array( 'fields_message' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'fields' => array( 'cols' => array( 0,
1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'buttons' => array( 'cols' => array( 0,
1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'user_fields_reset',
'user_fields_save' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 8 ),
'section' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 1 ),
'section1' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'changepwd_link' ),
'items' => array( 'changepassword_link' ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'twofactor_label',
'twofactor_comment' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'twofactor_setup_comment',
'twofactor_settings' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ) ) ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'userinfo',
'type' => 'userinfo',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'text3' ),
'align' => 'center' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'edit_field_label',
'integrated_edit_field3',
'edit_field_tooltip' ),
'width' => '50%' ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'text1',
'integrated_edit_field' ),
'bold' => true ),
'c1' => array( 'model' => 'c1',
'items' => array( 'user_fields_title' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'userinfo-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => '2factor_label',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => '2factor_label2',
'colspan' => 1 ),
array( 'cell' => '2factor_label3' ) ) ),
array( 'cells' => array( array( 'cell' => '2factor_label4',
'colspan' => 1 ),
array( 'cell' => '2factor_label1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => '2factor',
'colspan' => 2 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'fields_message3',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'fields_message',
'colspan' => 2 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'fields',
'colspan' => 2 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'buttons',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'fields_message' => array( 'model' => 'fields_message',
'items' => array( 'fields_message' ),
'align' => 'center' ),
'buttons' => array( 'model' => 'buttons',
'items' => array( 'user_fields_reset',
'user_fields_save' ) ),
'fields' => array( 'model' => 'fields',
'items' => array(  ) ),
'fields_message3' => array( 'model' => 'fields_message',
'items' => array(  ),
'align' => 'center',
'bold' => true,
'color' => '#00293c' ),
'2factor' => array( 'model' => '2factor',
'items' => array(  ) ),
'2factor_label1' => array( 'model' => '2factor_label',
'items' => array( 'tabs1' ),
'bold' => true ),
'2factor_label2' => array( 'model' => '2factor_label',
'items' => array( 'text2' ),
'align' => 'center',
'color' => '#00293c' ),
'2factor_label3' => array( 'model' => '2factor_label',
'items' => array( 'text4' ),
'align' => 'center',
'bold' => true,
'color' => '#00293c' ),
'2factor_label4' => array( 'model' => '2factor_label',
'items' => array( 'tabs' ),
'align' => 'left',
'bold' => true ),
'2factor_label' => array( 'model' => '2factor_label',
'items' => array( 'text' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 3,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field7' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'changepassword_link' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'twofactor_setup_comment',
'twofactor_settings' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'twofactor_label',
'twofactor_comment' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'fields_message' => array( 'type' => 'fields_message' ),
'user_fields_reset' => array( 'type' => 'user_fields_reset' ),
'user_fields_save' => array( 'type' => 'user_fields_save' ),
'user_fields_title' => array( 'type' => 'user_fields_title',
'font-size' => '24px' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'main' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'integrated_edit_field' => array( 'field' => 'username',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field1' => array( 'field' => 'fullname',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field2' => array( 'field' => 'email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'userpic',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'width' => '25%' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<br>',
'type' => 0 ),
'editedByRte' => false ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'notifications' => array( 'type' => 'notifications' ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'userpic',
'separated' => true,
'label' => array( 'field' => 'userpic',
'table' => 'public.hispmdusers',
'type' => 3 ) ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'userpic',
'separated' => true ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Name',
'type' => 0 ),
array( 'text' => 'Contact',
'type' => 0 ),
array( 'text' => 'Organisation',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section2' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field4' => array( 'field' => 'first_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'middle_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'last_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'phone_number',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'organisation_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'department',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'Hello 👋🏽 @',
'type' => 0 ),
'editedByRte' => false ),
'integrated_edit_field10' => array( 'field' => 'designation',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field11' => array( 'field' => 'apikey',
'type' => 'integrated_edit_field',
'orientation' => 0,
'bold' => true ),
'integrated_edit_field12' => array( 'field' => 'ext_security_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'bold' => true ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'Personal Information',
'type' => 0 ),
'editedByRte' => false,
'font-size' => '21px',
'color' => '#00293c',
'bold' => true ),
'twofactor_settings' => array( 'type' => 'twofactor_settings' ),
'twofactor_comment' => array( 'type' => 'twofactor_comment' ),
'twofactor_setup_comment' => array( 'type' => 'twofactor_setup_comment' ),
'twofactor_label' => array( 'type' => 'twofactor_label',
'font-size' => '24px' ),
'tabs1' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => '2FA',
'type' => 0 ),
array( 'text' => 'Password',
'type' => 0 ),
array( 'text' => 'Keys',
'type' => 0 ) ),
'locations' => array( 'section5',
'section3',
'section6' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => '<br>',
'type' => 0 ),
'editedByRte' => false ),
'text4' => array( 'type' => 'text',
'label' => array( 'text' => 'Security',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'color' => '#00293c',
'font-size' => '21px' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'standard',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>