<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'register_activate_message',
'register_activated_message',
'snippet',
'text' ),
'supertop' => array(  ),
'top' => array( 'image',
'register_success_header' ),
'grid' => array( 'register_proceed',
'register_close' ),
'footer' => array(  ) ),
'formXtTags' => array( 'supertop' => array(  ),
'footer' => array(  ) ),
'itemForms' => array( 'register_activate_message' => 'above-grid',
'register_activated_message' => 'above-grid',
'snippet' => 'above-grid',
'text' => 'above-grid',
'image' => 'top',
'register_success_header' => 'top',
'register_proceed' => 'grid',
'register_close' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'register_proceed' => array( 'register_proceed' ),
'register_success_header' => array( 'register_success_header' ),
'register_close' => array( 'register_close' ),
'image' => array( 'image' ),
'register_activate_message' => array( 'register_activate_message' ),
'register_activated_message' => array( 'register_activated_message' ),
'snippet' => array( 'snippet' ),
'text' => array( 'text' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array( 'register_activate_message' => array( 'tag' => 'REGISTER_ACTIVATE',
'type' => 2 ) ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'register_success',
'type' => 'register_success',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'register_success-above',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'register_activate_message',
'register_activated_message' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'snippet' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'text' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'register_success-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'image',
'register_success_header' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'register_success-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'register_proceed',
'register_close' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'register_success-footer',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'register_proceed' => array( 'type' => 'register_proceed' ),
'register_success_header' => array( 'type' => 'register_success_header' ),
'register_close' => array( 'type' => 'register_close' ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'MOH_logo_text_250.png',
'source' => 2 ) ),
'register_activate_message' => array( 'type' => 'register_activate_message' ),
'register_activated_message' => array( 'type' => 'register_activated_message' ),
'snippet' => array( 'eventId' => '_global__snippet',
'label' => array( 'text' => '_global__snippet',
'type' => 0 ),
'type' => 'snippet' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<p><strong>Please make sure to <u>COPY</u> your <u>API Key</u> and store it in a secure place!</strong></p>',
'type' => 0 ),
'editedByRte' => true ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>