<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'data_set',
'report_period',
'org_unit',
'facility_types',
'ownership_types' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'data_set' => array( 'integrated_edit_field' ),
'report_period' => array( 'integrated_edit_field1' ),
'org_unit' => array( 'integrated_edit_field2' ),
'facility_types' => array( 'integrated_edit_field5' ),
'ownership_types' => array( 'integrated_edit_field3' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'text4',
'text',
'text1',
'text2' ),
'below-grid' => array( 'view_back_list',
'view_close',
'text3',
'hamburger' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'notifications',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'view_header' ),
'grid' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field5' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'text4' => 'above-grid',
'text' => 'above-grid',
'text1' => 'above-grid',
'text2' => 'above-grid',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'text3' => 'below-grid',
'hamburger' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'view_header' => 'top',
'integrated_edit_field' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field5' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c6' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'notifications' => array( 'notifications' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field5',
'integrated_edit_field3' ),
'text' => array( 'text',
'text1',
'text2',
'text3',
'text4' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3',
'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'text4' ),
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'text' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'text1' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'text2' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'text3',
'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c5' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c6' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ),
'border' => array( array( 'side' => '',
'width' => '1px',
'color' => '#007abc' ) ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1' ),
'border' => array( array( 'side' => '',
'width' => '1px',
'color' => '#007abc' ) ) ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ),
'border' => array( array( 'side' => '',
'width' => '1px',
'color' => '#007abc' ) ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field3',
'integrated_edit_field5' ),
'border' => array( array( 'side' => '',
'width' => '1px',
'color' => '#007abc' ) ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header',
'title' => array( 'page' => 'view',
'table' => 'public.dhis2_reportingrate_settings',
'type' => 7 ) ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'notifications' => array( 'type' => 'notifications' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field' => array( 'field' => 'data_set',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field1' => array( 'field' => 'report_period',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field2' => array( 'field' => 'org_unit',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field5' => array( 'field' => 'facility_types',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'text' => array( 'type' => 'text',
'label' => array( 'label' => '__DOCTYPE_HTML___HTML_LANG__EN_____HEAD_______META_CHARSET__UTF_8________META_NAME__VIEWPORT__CONTENT__WIDTH_DEVICE_WIDTH__INITIAL_SCALE_1_0________TITLE_UPDATE_REPORTING_RATES__TITLE____________INCLUDE_BOOTSTRAP_CSS_FOR_MODERN_LOOK__________LINK_HREF__HTTPS___CDN_JSDELIVR_NET_NPM_BOOTSTRAP_5_3_0_ALPHA1_DIST_CSS_BOOTSTRAP_MIN_CSS__REL__STYLESHEET_________STYLE__________BODY_______________BACKGROUND_COLOR___F1F5F9______________FONT_FAMILY___ARIAL___SANS_SERIF______________PADDING__20PX______________________CONTAINER_______________MAX_WIDTH__600PX______________MARGIN__0_AUTO______________BACKGROUND___FFFFFF______________BORDER_RADIUS__10PX______________BOX_SHADOW__0_4PX_6PX_RGBA_0__0__0__0_1_______________PADDING__20PX_____________________H1_______________FONT_SIZE__1_8REM______________FONT_WEIGHT__BOLD______________COLOR___333______________________PROGRESS_CONTAINER_______________MARGIN_TOP__20PX______________________LOG_CONTAINER_______________MARGIN_TOP__20PX______________MAX_HEIGHT__300PX______________OVERFLOW_Y__AUTO______________BACKGROUND___F8F9FA______________PADDING__15PX______________BORDER__1PX_SOLID__DEE2E6______________BORDER_RADIUS__5PX______________________LOG_CONTAINER_PRE_______________MARGIN__0______________FONT_SIZE__14PX______________COLOR___495057______________WHITE_SPACE__PRE_WRAP______________________BTN_LG_______________FONT_SIZE__1REM______________PADDING__10PX_20PX______________________PROGRESS_BAR_______________TRANSITION__WIDTH_0_4S_EASE_____________________FOOTER_______________MARGIN_TOP__20PX______________TEXT_ALIGN__CENTER______________FONT_SIZE__0_9REM______________COLOR___6C757D_____________________FOOTER_A_______________COLOR___007BFF______________TEXT_DECORATION__NONE_____________________FOOTER_A_HOVER_______________TEXT_DECORATION__UNDERLINE__________________STYLE____HEAD____BODY_______DIV_CLASS__CONTAINER____________DIV_ALIGN__CENTER___SVG_WIDTH__64PX__HEIGHT__64PX__VIEWBOX__0_0_48_48__FILL__NONE__XMLNS__HTTP___WWW_W3_ORG_2000_SVG___G_ID__SVGREPO_BGCARRIER__STROKE_WIDTH__0____G__G_ID__SVGREPO_TRACERCARRIER__STROKE_LINECAP__ROUND__STROKE_LINEJOIN__ROUND____G__G_ID__SVGREPO_ICONCARRIER____PATH_FILL_RULE__EVENODD__CLIP_RULE__EVENODD__D__M8_05655_23_9708L6_86383_24_7067C5_64458_25_4589_5_58843_27_2115_6_75703_28_0402L22_8484_39_4515C23_5388_39_9411_24_4626_39_9431_25_1551_39_4565L41_3962_28_0456C42_5744_27_2178_42_5181_25_4536_41_2895_24_7026L39_8479_23_8215L38_0784_25_0839L40_2464_26_4091L24_0054_37_8201L7_91396_26_4088L9_84309_25_2186L8_05655_23_9708ZM33_4418_22_2498L24_0049_16_4814L14_4796_22_3581L12_693_21_1103L22_9547_14_7793C23_596_14_3837_24_4051_14_382_25_0479_14_775L35_2113_20_9873L33_4418_22_2498Z__FILL___3276C3____PATH___PATH_FILL_RULE__EVENODD__CLIP_RULE__EVENODD__D__M24_0048_9_48139L7_91391_19_4087L24_0053_30_82L40_2464_19_4091L24_0048_9_48139ZM6_86378_17_7066C5_64453_18_4588_5_58838_20_2114_6_75698_21_0401L22_8484_32_4514C23_5388_32_941_24_4626_32_943_25_1551_32_4565L41_3961_21_0455C42_5744_20_2177_42_518_18_4536_41_2894_17_7026L25_0479_7_77494C24_4051_7_38199_23_5959_7_38367_22_9547_7_77927L6_86378_17_7066Z__FILL___3276C3____PATH____G___SVG___DIV___________H2_CLASS__TEXT_CENTER_MB_4__UPDATE__U_DHIS2__U__REPORTING_RATES__H2____________DIV_CLASS__TEXT_CENTER________________BUTTON_ID__STARTUPDATE__CLASS__BTN_BTN_PRIMARY_BTN_LG__UPDATE_REPORTING_RATES__BUTTON____________DIV____________DIV_CLASS__PROGRESS_CONTAINER________________DIV_CLASS__PROGRESS____________________DIV_ID__PROGRESSBAR__CLASS__PROGRESS_BAR_BG_SUCCESS__ROLE__PROGRESSBAR__STYLE__WIDTH__0___ARIA_VALUENOW__0__ARIA_VALUEMIN__0__ARIA_VALUEMAX__100__0___DIV________________DIV____________DIV____________DIV_CLASS__LOG_CONTAINER_MT_4________________H5_CLASS__MB_3__LOGS___H5_______________PRE_ID__LOG__CLICK_THE_BUTTON_TO_START_THE_UPDATE_PROCESS_____PRE____________DIV____________FOOTER__________________BUILT_WITH____BY__A_HREF__HTTPS___MERQCONSULTANCY_ORG__TARGET___BLANK__MERQ_CONSULTANCY_PLC_LLC__A_______________FOOTER________DIV____________INCLUDE_JQUERY__________SCRIPT_SRC__HTTPS___CODE_JQUERY_COM_JQUERY_3_6_0_MIN_JS____SCRIPT___________BOOTSTRAP_BUNDLE_JS__________SCRIPT_SRC__HTTPS___CDN_JSDELIVR_NET_NPM_BOOTSTRAP_5_3_0_ALPHA1_DIST_JS_BOOTSTRAP_BUNDLE_MIN_JS____SCRIPT________SCRIPT____________DOCUMENT__READY_FUNCTION______________________STARTUPDATE___ON__CLICK___FUNCTION______________________CONST_BUTTON_____THIS___________________CONST_PROGRESSBAR_______PROGRESSBAR____________________CONST_LOG_______LOG________________________RESET_PROGRESS_BAR_AND_LOG_________________PROGRESSBAR_CSS__WIDTH____0____ATTR__ARIA_VALUENOW___0__TEXT__0_____________________LOG_HTML__________CLEAR_LOGS_________________BUTTON_PROP__DISABLED___TRUE__TEXT__UPDATING___________________________SIMULATE_THE_UPDATE_PROCESS___________________AJAX_______________________URL______API_DHIS2_APIS_UPDATE_REPORTING_RATES_PHP_______________________TYPE___GET_______________________XHR__FUNCTION______________________________CONST_XHR___NEW_WINDOW_XMLHTTPREQUEST________________________________UPDATE_PROGRESS_AND_LOG_IN_REAL_TIME_________________________XHR_ONPROGRESS___FUNCTION__E________________________________IF__E_LENGTHCOMPUTABLE____________________________________CONST_PROGRESS___MATH_FLOOR__E_LOADED___E_TOTAL____100___________________________________PROGRESSBAR_CSS__WIDTH___PROGRESS________ATTR__ARIA_VALUENOW___PROGRESS__TEXT_PROGRESS____________________________________________________________________CONST_NEWLOG___E_TARGET_RESPONSETEXT______________________________LOG_HTML_NEWLOG_______UPDATE_LOG_DIV_WITH_NEW_LOG_DATA_____________________________________________________RETURN_XHR_____________________________________________SUCCESS__FUNCTION__RESPONSE____________________________PROGRESSBAR_CSS__WIDTH____100____ATTR__ARIA_VALUENOW___100__TEXT__100_____________________________BUTTON_PROP__DISABLED___FALSE__TEXT__UPDATE_REPORTING_RATES____________________________LOG_APPEND___PRE_UPDATE_COMPLETED_SUCCESSFULLY___PRE________________________________________________ERROR__FUNCTION__XHR__STATUS__ERROR____________________________LOG_APPEND___PRE_ERROR____ERROR___PRE_____________________________BUTTON_PROP__DISABLED___FALSE__TEXT__UPDATE_REPORTING_RATES________________________________________________________________________________SCRIPT____BODY_____HTML__',
'table' => null,
'type' => 1 ),
'editedByRte' => false ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => '<br>
<br>
<br>',
'type' => 0 ),
'editedByRte' => false ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => '<p><strong>To Update Reporting Rates Data:</strong> Make sure to update the settings below are correctly set!</p>',
'type' => 0 ),
'editedByRte' => true ),
'text3' => array( 'type' => 'text',
'label' => array( 'label' => '_P_CLICK_ON_THE_BUTTON_TO_EDIT_THE_SETTINGS__STRONG___GT___STRONG___P_',
'type' => 1 ),
'editedByRte' => true,
'bold' => true ),
'text4' => array( 'type' => 'text',
'label' => array( 'text' => '<br>',
'type' => 0 ),
'editedByRte' => false,
'bold' => true ),
'integrated_edit_field3' => array( 'field' => 'ownership_types',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>