<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array( 'Organisation unit',
'Dataset ID',
'Facility Type',
'Ownership Type Label',
'Report Period' ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'Organisation unit ID' => array( 'totalsType' => '' ),
'Organisation unit' => array( 'totalsType' => '' ),
'Organisation unit code' => array( 'totalsType' => '' ),
'Organisation unit description' => array( 'totalsType' => '' ),
'actual reports' => array( 'totalsType' => '' ),
'expected reports' => array( 'totalsType' => '' ),
'reporting rate' => array( 'totalsType' => '' ),
'actual reports on time' => array( 'totalsType' => '' ),
'reporting rate on time' => array( 'totalsType' => '' ),
'Dataset ID' => array( 'totalsType' => '' ),
'Dataset Name' => array( 'totalsType' => '' ),
'Facility Type' => array( 'totalsType' => '' ),
'Ownership Type ID' => array( 'totalsType' => '' ),
'Ownership Type Label' => array( 'totalsType' => '' ),
'Report Period' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Organisation unit',
'Dataset ID',
'Facility Type',
'Ownership Type Label',
'Report Period',
'actual reports',
'expected reports',
'reporting rate',
'actual reports on time',
'reporting rate on time' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'Organisation unit',
'Dataset ID',
'Facility Type',
'Ownership Type Label',
'Report Period' ),
'filterFields' => array( 'Organisation unit',
'Facility Type',
'Ownership Type Label' ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'Organisation unit' => array( 'grid_field1',
'grid_field_label1' ),
'actual reports' => array( 'grid_field4' ),
'expected reports' => array( 'grid_field5' ),
'reporting rate' => array( 'grid_field6' ),
'actual reports on time' => array( 'grid_field7' ),
'reporting rate on time' => array( 'grid_field8' ),
'Dataset ID' => array( 'grid_field9',
'grid_field_label9' ),
'Facility Type' => array( 'grid_field11',
'grid_field_label11' ),
'Report Period' => array( 'grid_field12',
'grid_field_label12' ),
'Ownership Type Label' => array( 'grid_field2',
'grid_field_label2' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'details_found',
'page_size',
'print_panel',
'text12',
'text9',
'text8',
'filter_panel',
'text1',
'text11',
'text',
'text10',
'text2' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ),
'grid' => array( 'grid_field_label9',
'grid_field9',
'text3',
'grid_field4',
'text4',
'grid_field5',
'text5',
'grid_field6',
'text6',
'grid_field7',
'text7',
'grid_field8',
'grid_checkbox_head',
'grid_checkbox',
'grid_field_label1',
'grid_field1',
'grid_field_label12',
'grid_field12',
'grid_field_label11',
'grid_field11',
'grid_field_label2',
'grid_field2' ),
'top' => array(  ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'text12' => 'above-grid',
'text9' => 'above-grid',
'text8' => 'above-grid',
'filter_panel' => 'above-grid',
'text1' => 'above-grid',
'text11' => 'above-grid',
'text' => 'above-grid',
'text10' => 'above-grid',
'text2' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'text3' => 'grid',
'grid_field4' => 'grid',
'text4' => 'grid',
'grid_field5' => 'grid',
'text5' => 'grid',
'grid_field6' => 'grid',
'text6' => 'grid',
'grid_field7' => 'grid',
'text7' => 'grid',
'grid_field8' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label12' => 'grid',
'grid_field12' => 'grid',
'grid_field_label11' => 'grid',
'grid_field11' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid' ),
'itemLocations' => array( 'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'text3' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'text4' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'text5' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'text6' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'text7' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field_label12' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'grid_field12' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'grid_field_label11' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'export' => array( 'export' ),
'-' => array( '-',
'-1',
'-2',
'-3' ),
'import' => array( 'import' ),
'advsearch_link' => array( 'advsearch_link' ),
'filter_panel' => array( 'filter_panel' ),
'filter_panel_field' => array( 'filter_panel_field',
'filter_panel_field1',
'filter_panel_field2' ),
'text' => array( 'text',
'text1',
'text2',
'text3',
'text4',
'text5',
'text6',
'text7',
'text8',
'text9',
'text10',
'text11',
'text12' ),
'username_button' => array( 'username_button' ),
'adminarea_link' => array( 'adminarea_link' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'notifications' => array( 'notifications' ),
'changepassword_link' => array( 'changepassword_link' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'grid_field' => array( 'grid_field1',
'grid_field4',
'grid_field5',
'grid_field6',
'grid_field7',
'grid_field8',
'grid_field9',
'grid_field11',
'grid_field12',
'grid_field2' ),
'grid_field_label' => array( 'grid_field_label1',
'grid_field_label9',
'grid_field_label11',
'grid_field_label12',
'grid_field_label2' ),
'search_panel_field' => array( 'search_panel_field9',
'search_panel_field11',
'search_panel_field12',
'search_panel_field',
'search_panel_field1' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'Organisation_unit_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Dataset_ID_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Facility_Type_fieldheadercolumn' ),
'items' => array( 'grid_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Ownership_Type_Label_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'Report_Period_fieldheadercolumn' ),
'items' => array( 'grid_field_label12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'Organisation_unit_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Dataset_ID_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Facility_Type_fieldcolumn' ),
'items' => array( 'grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Ownership_Type_Label_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'Report_Period_fieldcolumn' ),
'items' => array( 'grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'actual_reports_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'expected_reports_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'reporting_rate_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'actual_reports_on_time_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'reporting_rate_on_time_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 11,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c6',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'text12' ),
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'text9',
'text8',
'filter_panel' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'text1' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'text11',
'text' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'text10',
'text2' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'search_panel' ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label9' ),
'field' => 'Dataset ID',
'columnName' => 'field' ),
'headcell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'Dataset ID',
'columnName' => 'field' ),
'headcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'text3' ) ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'align' => 'center',
'field' => 'actual reports',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'text4' ) ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'align' => 'center',
'field' => 'expected reports',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'text5' ) ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'align' => 'center',
'background' => '#e7feff',
'field' => 'reporting rate',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'text6' ) ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'align' => 'center',
'field' => 'actual reports on time',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'text7' ) ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'align' => 'center',
'background' => '#e7feff',
'field' => 'reporting rate on time',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'Organisation unit',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'Organisation unit',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label12' ),
'field' => 'Report Period',
'columnName' => 'field' ),
'headcell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field12' ),
'field' => 'Report Period',
'columnName' => 'field' ),
'headcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label11' ),
'field' => 'Facility Type',
'columnName' => 'field' ),
'headcell_field15' => array( 'model' => 'cell_field',
'items' => array( 'grid_field11' ),
'field' => 'Facility Type',
'columnName' => 'field' ),
'headcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'field' => 'Ownership Type Label',
'columnName' => 'field' ),
'headcell_field18' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'Ownership Type Label',
'columnName' => 'field' ),
'headcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'main' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field9',
'search_panel_field11',
'search_panel_field1',
'search_panel_field12' ),
'_flexiblePanel' => true ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-2',
'export',
'-1',
'import',
'-3' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-2' => array( 'type' => '-' ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field',
'filter_panel_field1',
'filter_panel_field2' ) ),
'filter_panel_field' => array( 'field' => 'Organisation unit',
'type' => 'filter_panel_field' ),
'text' => array( 'type' => 'text',
'label' => array( 'label' => 'START_HERE_BY_SELECTING_AN_ORGANISATION_UNIT____DATASET_AND_THEN_REPORT_PERIOD_THE_AND_CLICK_ON_SEARCH',
'type' => 1 ),
'editedByRte' => false ),
'text1' => array( 'type' => 'text',
'label' => array( 'label' => 'AFTER_SELECTING_FROM_THE_ABOVE_AVAILABLE_DATASETS_AND_ORGANISATION_UNITS__YOU_CAN_USE_THE_FILTERS_BELOW_TO_NARROW_DOWN_YOUR_SEARCH_RESULTS_',
'type' => 1 ),
'editedByRte' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'notifications' => array( 'type' => 'notifications' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'-3' => array( 'type' => '-' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'grid_field1' => array( 'field' => 'Organisation unit',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true,
'color' => '#337ab7' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'Organisation unit' ),
'grid_field4' => array( 'field' => 'actual reports',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true ),
'grid_field5' => array( 'field' => 'expected reports',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true ),
'grid_field6' => array( 'field' => 'reporting rate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true ),
'grid_field7' => array( 'field' => 'actual reports on time',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true ),
'grid_field8' => array( 'field' => 'reporting rate on time',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true ),
'grid_field9' => array( 'field' => 'Dataset ID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'Dataset ID' ),
'search_panel_field9' => array( 'field' => 'Dataset ID',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'grid_field11' => array( 'field' => 'Facility Type',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label11' => array( 'type' => 'grid_field_label',
'field' => 'Facility Type' ),
'search_panel_field11' => array( 'field' => 'Facility Type',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'grid_field12' => array( 'field' => 'Report Period',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label12' => array( 'type' => 'grid_field_label',
'field' => 'Report Period' ),
'search_panel_field12' => array( 'field' => 'Report Period',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'DHIS2 Reporting Rate Details',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'italic' => true ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => 'Actual Reports',
'type' => 0 ),
'editedByRte' => false ),
'text4' => array( 'type' => 'text',
'label' => array( 'text' => 'Expected Reports',
'type' => 0 ),
'editedByRte' => false ),
'text5' => array( 'type' => 'text',
'label' => array( 'type' => 0,
'text' => 'Reporting Rate (%)' ),
'editedByRte' => false ),
'text6' => array( 'type' => 'text',
'label' => array( 'text' => 'Actual Reports On Time',
'type' => 0 ),
'editedByRte' => false ),
'text7' => array( 'type' => 'text',
'label' => array( 'type' => 0,
'text' => 'Reporting Rate On Time (%)' ),
'editedByRte' => false ),
'text8' => array( 'type' => 'text',
'label' => array( 'text' => '<br><br><br>',
'type' => 0 ),
'editedByRte' => false ),
'text9' => array( 'type' => 'text',
'label' => array( 'text' => '<br>',
'type' => 0 ),
'editedByRte' => false ),
'filter_panel_field1' => array( 'field' => 'Facility Type',
'type' => 'filter_panel_field' ),
'search_panel_field' => array( 'field' => 'Organisation unit',
'type' => 'search_panel_field',
'alwaysOnPanel' => true,
'required' => false ),
'grid_field2' => array( 'field' => 'Ownership Type Label',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'Ownership Type Label' ),
'search_panel_field1' => array( 'field' => 'Ownership Type Label',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'filter_panel_field2' => array( 'field' => 'Ownership Type Label',
'type' => 'filter_panel_field' ),
'text10' => array( 'type' => 'text',
'label' => array( 'text' => '<br>',
'type' => 0 ),
'editedByRte' => false ),
'text11' => array( 'type' => 'text',
'label' => array( 'text' => '👈',
'type' => 0 ),
'editedByRte' => false,
'color' => '#00b5ff',
'bold' => true ),
'text12' => array( 'type' => 'text',
'label' => array( 'label' => '_BR__BR__BR_',
'type' => 1 ),
'editedByRte' => false ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 11,
'reorderRows' => false,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>