<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'actual_reports',
'expected_reports',
'reporting_rate',
'actual_reports_on_time',
'reporting_rate_on_time',
'report_period',
'ownership_type_label' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'actual_reports' => array( 'report_grid_field3' ),
'expected_reports' => array( 'report_grid_field4' ),
'reporting_rate' => array( 'report_grid_field5' ),
'actual_reports_on_time' => array( 'report_grid_field6' ),
'reporting_rate_on_time' => array( 'report_grid_field7' ),
'report_period' => array( 'report_grid_field11' ),
'dataset_name' => array( 'report_group_field' ),
'organisationunit' => array( 'report_group_field1' ),
'facility_type' => array( 'report_group_field2' ),
'ownership_type_label' => array( 'report_grid_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field11',
'report_grid_field' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_group_field2' => 'grid',
'report_grid_field3' => 'grid',
'report_grid_field4' => 'grid',
'report_grid_field5' => 'grid',
'report_grid_field6' => 'grid',
'report_grid_field7' => 'grid',
'report_grid_field11' => 'grid',
'report_grid_field' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'report_grid_field' => array( 'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field11',
'report_grid_field' ),
'report_group_field' => array( 'report_group_field',
'report_group_field1',
'report_group_field2' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'rprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '94CACA',
'summary' => 'AFEEEE' ),
'field' => 'dataset_name' ),
array( 'interval' => 0,
'summary' => false,
'axis' => 0,
'color' => array( 'header' => 'D8D8BE',
'summary' => 'FFFFE0' ),
'field' => 'organisationunit' ),
array( 'interval' => 0,
'summary' => false,
'axis' => 0,
'color' => array( 'header' => 'D8A3AC',
'summary' => 'FFC0CB' ),
'field' => 'facility_type' ) ),
'fields' => array( array( 'avg' => true,
'field' => 'actual_reports',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'expected_reports',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'reporting_rate',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'actual_reports_on_time',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'reporting_rate_on_time',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => false,
'field' => 'report_period',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'ownership_type_label',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ) ),
'showData' => true,
'pageSummary' => false,
'globalSummary' => false,
'crosstab' => false,
'colors' => array(  ),
'horizSummary' => false,
'layout' => 'block',
'vertSummary' => false ) ) );
			$pageArray = array( 'id' => 'rprint',
'type' => 'rprint',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1',
'report_group_field2' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field11',
'report_grid_field' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '94CACA',
'summary' => 'AFEEEE' ),
'field' => 'dataset_name' ),
array( 'interval' => 0,
'summary' => false,
'axis' => 0,
'color' => array( 'header' => 'D8D8BE',
'summary' => 'FFFFE0' ),
'field' => 'organisationunit' ),
array( 'interval' => 0,
'summary' => false,
'axis' => 0,
'color' => array( 'header' => 'D8A3AC',
'summary' => 'FFC0CB' ),
'field' => 'facility_type' ) ),
'fields' => array( array( 'avg' => true,
'field' => 'actual_reports',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'expected_reports',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'reporting_rate',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'actual_reports_on_time',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'reporting_rate_on_time',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => false,
'field' => 'report_period',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'ownership_type_label',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ) ),
'showData' => true,
'pageSummary' => false,
'globalSummary' => false,
'crosstab' => false,
'colors' => array(  ),
'horizSummary' => false,
'layout' => 'block',
'vertSummary' => false ) ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'report_grid_field3' => array( 'field' => 'actual_reports',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field4' => array( 'field' => 'expected_reports',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field5' => array( 'field' => 'reporting_rate',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field6' => array( 'field' => 'actual_reports_on_time',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field7' => array( 'field' => 'reporting_rate_on_time',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field11' => array( 'field' => 'report_period',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_group_field' => array( 'field' => 'dataset_name',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field1' => array( 'field' => 'organisationunit',
'type' => 'report_group_field',
'summary' => false,
'axis' => 0,
'interval' => 0 ),
'report_group_field2' => array( 'field' => 'facility_type',
'type' => 'report_group_field',
'summary' => false,
'axis' => 0,
'interval' => 0 ),
'report_grid_field' => array( 'field' => 'ownership_type_label',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>