<?php
			$optionsArray = array( 'totals' => array( 'THIS_WEEK' => array( 'totalsType' => '' ),
'LAST_WEEK' => array( 'totalsType' => '' ),
'LAST_4_WEEKS' => array( 'totalsType' => '' ),
'LAST_12_WEEKS' => array( 'totalsType' => '' ),
'LAST_52_WEEKS' => array( 'totalsType' => '' ),
'THIS_MONTH' => array( 'totalsType' => '' ),
'LAST_MONTH' => array( 'totalsType' => '' ),
'THIS_BIMONTH' => array( 'totalsType' => '' ),
'LAST_BIMONTH' => array( 'totalsType' => '' ),
'THIS_QUARTER' => array( 'totalsType' => '' ),
'LAST_QUARTER' => array( 'totalsType' => '' ),
'THIS_SIX_MONTH' => array( 'totalsType' => '' ),
'LAST_SIX_MONTH' => array( 'totalsType' => '' ),
'MONTHS_THIS_YEAR' => array( 'totalsType' => '' ),
'QUARTERS_THIS_YEAR' => array( 'totalsType' => '' ),
'THIS_YEAR' => array( 'totalsType' => '' ),
'MONTHS_LAST_YEAR' => array( 'totalsType' => '' ),
'QUARTERS_LAST_YEAR' => array( 'totalsType' => '' ),
'LAST_YEAR' => array( 'totalsType' => '' ),
'LAST_5_YEARS' => array( 'totalsType' => '' ),
'LAST_12_MONTHS' => array( 'totalsType' => '' ),
'LAST_3_MONTHS' => array( 'totalsType' => '' ),
'LAST_6_BIMONTHS' => array( 'totalsType' => '' ),
'LAST_4_QUARTERS' => array( 'totalsType' => '' ),
'LAST_2_SIXMONTHS' => array( 'totalsType' => '' ),
'THIS_FINANCIAL_YEAR' => array( 'totalsType' => '' ),
'LAST_FINANCIAL_YEAR' => array( 'totalsType' => '' ),
'LAST_5_FINANCIAL_YEARS' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array(  ),
'exportFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array(  ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ),
'grid' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>