<?php
			$optionsArray = array( 'totals' => array( 'SubmissionDate' => array( 'totalsType' => '' ),
'starttime' => array( 'totalsType' => '' ),
'endtime' => array( 'totalsType' => '' ),
'deviceid' => array( 'totalsType' => '' ),
'subscriberid' => array( 'totalsType' => '' ),
'simid' => array( 'totalsType' => '' ),
'devicephonenum' => array( 'totalsType' => '' ),
'username' => array( 'totalsType' => '' ),
'duration' => array( 'totalsType' => '' ),
'caseid' => array( 'totalsType' => '' ),
'DQ104' => array( 'totalsType' => '' ),
'intvwr_vst_DQ101' => array( 'totalsType' => '' ),
'intvwr_vst_DQ102' => array( 'totalsType' => '' ),
'intvwr_vst_DQ102_Other' => array( 'totalsType' => '' ),
'distr_unit_id_DQ105' => array( 'totalsType' => '' ),
'distr_unit_id_DQ106' => array( 'totalsType' => '' ),
'distr_unit_id_DQ106_Other' => array( 'totalsType' => '' ),
'distr_unit_id_DQ108' => array( 'totalsType' => '' ),
'siteid' => array( 'totalsType' => '' ),
'gen_info_DQ109' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'SubmissionDate',
'starttime',
'endtime',
'deviceid',
'subscriberid',
'simid',
'devicephonenum',
'username',
'duration',
'caseid',
'DQ104',
'intvwr_vst_DQ101',
'intvwr_vst_DQ102',
'intvwr_vst_DQ102_Other',
'distr_unit_id_DQ105',
'distr_unit_id_DQ106',
'distr_unit_id_DQ106_Other',
'distr_unit_id_DQ108',
'siteid',
'gen_info_DQ109' ),
'exportFields' => array( 'SubmissionDate',
'starttime',
'endtime',
'deviceid',
'subscriberid',
'simid',
'devicephonenum',
'username',
'duration',
'caseid',
'DQ104',
'intvwr_vst_DQ101',
'intvwr_vst_DQ102',
'intvwr_vst_DQ102_Other',
'distr_unit_id_DQ105',
'distr_unit_id_DQ106',
'distr_unit_id_DQ106_Other',
'distr_unit_id_DQ108',
'siteid',
'gen_info_DQ109' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'SubmissionDate' => array( 'export_field' ),
'starttime' => array( 'export_field1' ),
'endtime' => array( 'export_field2' ),
'deviceid' => array( 'export_field3' ),
'subscriberid' => array( 'export_field4' ),
'simid' => array( 'export_field5' ),
'devicephonenum' => array( 'export_field6' ),
'username' => array( 'export_field7' ),
'duration' => array( 'export_field8' ),
'caseid' => array( 'export_field9' ),
'DQ104' => array( 'export_field10' ),
'intvwr_vst_DQ101' => array( 'export_field11' ),
'intvwr_vst_DQ102' => array( 'export_field12' ),
'intvwr_vst_DQ102_Other' => array( 'export_field13' ),
'distr_unit_id_DQ105' => array( 'export_field14' ),
'distr_unit_id_DQ106' => array( 'export_field15' ),
'distr_unit_id_DQ106_Other' => array( 'export_field16' ),
'distr_unit_id_DQ108' => array( 'export_field17' ),
'siteid' => array( 'export_field18' ),
'gen_info_DQ109' => array( 'export_field19' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'SubmissionDate',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'starttime',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'endtime',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'deviceid',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'subscriberid',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'simid',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'devicephonenum',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'username',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'duration',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'caseid',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'DQ104',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'intvwr_vst_DQ101',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'intvwr_vst_DQ102',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'intvwr_vst_DQ102_Other',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'distr_unit_id_DQ105',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'distr_unit_id_DQ106',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'distr_unit_id_DQ106_Other',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'distr_unit_id_DQ108',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'siteid',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'gen_info_DQ109',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>