<?php
			$optionsArray = array( 'totals' => array( 'CompletionDate' => array( 'totalsType' => '' ),
'SubmissionDate' => array( 'totalsType' => '' ),
'starttime' => array( 'totalsType' => '' ),
'endtime' => array( 'totalsType' => '' ),
'deviceid' => array( 'totalsType' => '' ),
'subscriberid' => array( 'totalsType' => '' ),
'simid' => array( 'totalsType' => '' ),
'devicephonenum' => array( 'totalsType' => '' ),
'username' => array( 'totalsType' => '' ),
'duration' => array( 'totalsType' => '' ),
'caseid' => array( 'totalsType' => '' ),
'FQ104' => array( 'totalsType' => '' ),
'FQ101' => array( 'totalsType' => '' ),
'FQ102' => array( 'totalsType' => '' ),
'FQ103' => array( 'totalsType' => '' ),
'FQ105' => array( 'totalsType' => '' ),
'FQ106' => array( 'totalsType' => '' ),
'FQ107' => array( 'totalsType' => '' ),
'FQ108' => array( 'totalsType' => '' ),
'siteid' => array( 'totalsType' => '' ),
'FQ109' => array( 'totalsType' => '' ),
'FQ110' => array( 'totalsType' => '' ),
'FQ111' => array( 'totalsType' => '' ),
'FQ112' => array( 'totalsType' => '' ),
'FQ113' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'CompletionDate',
'SubmissionDate',
'starttime',
'endtime',
'deviceid',
'subscriberid',
'simid',
'devicephonenum',
'username',
'duration',
'caseid',
'FQ104',
'FQ101',
'FQ102',
'FQ103',
'FQ105',
'FQ106',
'FQ107',
'FQ108',
'siteid',
'FQ109',
'FQ110',
'FQ111',
'FQ112',
'FQ113' ),
'exportFields' => array( 'CompletionDate',
'SubmissionDate',
'starttime',
'endtime',
'deviceid',
'subscriberid',
'simid',
'devicephonenum',
'username',
'duration',
'caseid',
'FQ104',
'FQ101',
'FQ102',
'FQ103',
'FQ105',
'FQ106',
'FQ107',
'FQ108',
'siteid',
'FQ109',
'FQ110',
'FQ111',
'FQ112',
'FQ113' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'CompletionDate' => array( 'export_field' ),
'SubmissionDate' => array( 'export_field1' ),
'starttime' => array( 'export_field2' ),
'endtime' => array( 'export_field3' ),
'deviceid' => array( 'export_field4' ),
'subscriberid' => array( 'export_field5' ),
'simid' => array( 'export_field6' ),
'devicephonenum' => array( 'export_field7' ),
'username' => array( 'export_field8' ),
'duration' => array( 'export_field9' ),
'caseid' => array( 'export_field10' ),
'FQ104' => array( 'export_field11' ),
'FQ101' => array( 'export_field12' ),
'FQ102' => array( 'export_field13' ),
'FQ103' => array( 'export_field14' ),
'FQ105' => array( 'export_field15' ),
'FQ106' => array( 'export_field16' ),
'FQ107' => array( 'export_field17' ),
'FQ108' => array( 'export_field18' ),
'siteid' => array( 'export_field19' ),
'FQ109' => array( 'export_field20' ),
'FQ110' => array( 'export_field21' ),
'FQ111' => array( 'export_field22' ),
'FQ112' => array( 'export_field24' ),
'FQ113' => array( 'export_field654' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field24',
'export_field654' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field24' => 'grid',
'export_field654' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field24',
'export_field654' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field24',
'export_field654' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'CompletionDate',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'SubmissionDate',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'starttime',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'endtime',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'deviceid',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'subscriberid',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'simid',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'devicephonenum',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'username',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'duration',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'caseid',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'FQ104',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'FQ101',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'FQ102',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'FQ103',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'FQ105',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'FQ106',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'FQ107',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'FQ108',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'siteid',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'FQ109',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'FQ110',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'FQ111',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'FQ112',
'type' => 'export_field' ),
'export_field654' => array( 'field' => 'FQ113',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>