<?php
			$optionsArray = array( 'totals' => array( 'Indicator Group' => array( 'totalsType' => '' ),
'Indicator Name' => array( 'totalsType' => '' ),
'Facility Type' => array( 'totalsType' => '' ),
'Data Source' => array( 'totalsType' => '' ),
'Assessment' => array( 'totalsType' => '' ),
'Administration Unit' => array( 'totalsType' => '' ),
'Year' => array( 'totalsType' => '' ),
'Scope' => array( 'totalsType' => '' ),
'Region' => array( 'totalsType' => '' ),
'Gender/Sex' => array( 'totalsType' => '' ),
'Value' => array( 'totalsType' => '' ),
'Data Representation' => array( 'totalsType' => '' ),
'Data Source Detail' => array( 'totalsType' => '' ),
'Target Value' => array( 'totalsType' => '' ),
'Target Year' => array( 'totalsType' => '' ),
'Baseline Value' => array( 'totalsType' => '' ),
'Baseline Year' => array( 'totalsType' => '' ),
'Quarter ID' => array( 'totalsType' => '' ),
'Month ID' => array( 'totalsType' => '' ),
'Period ID' => array( 'totalsType' => '' ),
'Period' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Indicator Group',
'Indicator Name',
'Target Value',
'Target Year',
'Facility Type',
'Data Source',
'Assessment',
'Administration Unit',
'Year',
'Scope',
'Region',
'Gender/Sex',
'Value',
'Data Representation',
'Data Source Detail',
'Baseline Value',
'Baseline Year',
'Quarter ID',
'Month ID',
'Period ID',
'Period' ),
'exportFields' => array( 'Indicator Group',
'Indicator Name',
'Facility Type',
'Data Source',
'Assessment',
'Administration Unit',
'Year',
'Scope',
'Region',
'Gender/Sex',
'Value',
'Data Representation',
'Data Source Detail',
'Target Value',
'Target Year',
'Baseline Value',
'Baseline Year',
'Quarter ID',
'Month ID',
'Period ID',
'Period' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Indicator Group' => array( 'export_field' ),
'Indicator Name' => array( 'export_field1' ),
'Target Value' => array( 'export_field2' ),
'Target Year' => array( 'export_field3' ),
'Facility Type' => array( 'export_field4' ),
'Data Source' => array( 'export_field5' ),
'Assessment' => array( 'export_field6' ),
'Administration Unit' => array( 'export_field7' ),
'Year' => array( 'export_field8' ),
'Scope' => array( 'export_field9' ),
'Region' => array( 'export_field10' ),
'Gender/Sex' => array( 'export_field11' ),
'Value' => array( 'export_field12' ),
'Data Representation' => array( 'export_field13' ),
'Data Source Detail' => array( 'export_field14' ),
'Baseline Value' => array( 'export_field15' ),
'Baseline Year' => array( 'export_field16' ),
'Quarter ID' => array( 'export_field17' ),
'Month ID' => array( 'export_field18' ),
'Period ID' => array( 'export_field19' ),
'Period' => array( 'export_field20' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field2',
'export_field3',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field2',
'export_field3',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'Indicator Group',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'Indicator Name',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Target Value',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Target Year',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Facility Type',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Data Source',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Assessment',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Administration Unit',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Year',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'Scope',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Region',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Gender/Sex',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Value',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Data Representation',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Data Source Detail',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'Baseline Value',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'Baseline Year',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'Quarter ID',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'Month ID',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'Period ID',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'Period',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>