<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'kbcomments' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ) ),
'fields' => array( 'gridFields' => array( 'Solution',
'Title',
'DateCreated',
'Views',
'Problem',
'helpfullblock' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Solution' => array( 'integrated_edit_field5',
'edit_field_label2' ),
'Title' => array( 'integrated_edit_field6' ),
'DateCreated' => array( 'integrated_edit_field3',
'edit_field_label3' ),
'Views' => array( 'edit_field_label',
'integrated_edit_field7' ),
'Problem' => array( 'integrated_edit_field4',
'edit_field_label1' ),
'helpfullblock' => array( 'integrated_edit_field' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'top' => array(  ),
'grid' => array( 'integrated_edit_field',
'edit_field_label1',
'integrated_edit_field4',
'edit_field_label2',
'integrated_edit_field5',
'integrated_edit_field6',
'edit_field_label3',
'integrated_edit_field3',
'edit_field_label',
'integrated_edit_field7',
'details_preview',
'breadcrumb' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'top' => array(  ) ),
'itemForms' => array( 'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'integrated_edit_field' => 'grid',
'edit_field_label1' => 'grid',
'integrated_edit_field4' => 'grid',
'edit_field_label2' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field6' => 'grid',
'edit_field_label3' => 'grid',
'integrated_edit_field3' => 'grid',
'edit_field_label' => 'grid',
'integrated_edit_field7' => 'grid',
'details_preview' => 'grid',
'breadcrumb' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c' ),
'edit_field_label1' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'edit_field_label2' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'edit_field_label3' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'edit_field_label' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'breadcrumb' => array( 'location' => 'grid',
'cellId' => 'c12' ) ),
'itemVisiblity' => array( 'menu' => 3,
'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'edit_field' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field3',
'integrated_edit_field7',
'integrated_edit_field4',
'integrated_edit_field' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1',
'edit_field_label2',
'edit_field_label3' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'breadcrumb' => array( 'breadcrumb' ),
'details_preview' => array( 'details_preview' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c12' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'breadcrumb' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'edit_field_label3',
'integrated_edit_field3',
'edit_field_label',
'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'edit_field_label1',
'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'edit_field_label2',
'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 7 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'view',
'breadcrumb' => true,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'customCSS' => '/* Put  your custom CSS code here */

:host {
  margin-bottom:50px;
}
' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ) ),
'c3' => array( 'model' => 'c3',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11',
'rowspan' => 1,
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 1,
'rowspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ) ),
'c1' => array( 'model' => 'c3',
'items' => array( 'edit_field_label1',
'integrated_edit_field4' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
    border-bottom: 1px solid #e2e2e2;
}
' ),
'c4' => array( 'model' => 'c3',
'items' => array( 'edit_field_label2',
'integrated_edit_field5' ),
'padding' => array( 'top' => '20px' ) ),
'c10' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field6' ) ),
'c11' => array( 'model' => 'c2',
'items' => array( 'edit_field_label3',
'integrated_edit_field3',
'edit_field_label',
'integrated_edit_field7' ) ),
'c2' => array( 'model' => 'c3',
'items' => array( 'details_preview' ) ),
'c12' => array( 'model' => 'c2',
'items' => array( 'breadcrumb' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field5' => array( 'field' => 'Solution',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field6' => array( 'field' => 'Title',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'customCSS' => '/* Put  your custom CSS code here */

:host {
      font-size: 36px;
    line-height: 40px;
    font-weight: 400;
    color: #1b1b1b;
    margin-bottom: 40px;
}
' ),
'integrated_edit_field3' => array( 'field' => 'DateCreated',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'Views',
'separated' => true ),
'integrated_edit_field7' => array( 'field' => 'Views',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'integrated_edit_field4' => array( 'field' => 'Problem',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'kbcomments',
'items' => array(  ),
'popup' => false,
'pageId' => 'list',
'customCSS' => '/* Put  your custom CSS code here */

:host td{
 border-top: none;
}

:host .panel-heading{
    background:transparent;
    border: none;
    padding-left: 20px;

}
:host .panel-title{
    font-family: "Montserrat",sans-serif;
    color: #1b1b1b;
    font-weight: bold;
    
}

:host .r-gridrow{
    border-bottom: 1px solid #e2e2e2;
}

:host [data-field="comment"]{
    margin:10px 0 10px 0;
    display:block;
}
:host [data-field="email"]
{
    font-style: italic;
    color: #1b1b1b;
}


:host .panel.panel-info{
    border:none;
    box-shadow:none;
}' ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'Problem',
'separated' => true ),
'edit_field_label2' => array( 'type' => 'edit_field_label',
'field' => 'Solution',
'separated' => true ),
'edit_field_label3' => array( 'type' => 'edit_field_label',
'field' => 'DateCreated',
'separated' => true,
'label' => array( 'field' => 'DateCreated',
'table' => 'main',
'type' => 3 ) ),
'integrated_edit_field' => array( 'field' => 'helpfullblock',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ) ),
'dbProps' => array(  ),
'version' => 11,
'businessTemplate' => 'KnowledgeBase',
'businessTemplatePageId' => 'view',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>