<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => false,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'allDetails' => array( 'linkType' => 2 ),
'details' => array( 'kbcomments' => array( 'displayPreview' => 2,
'previewPageId' => '',
'showCount' => false,
'badgeColor' => '',
'hideEmptyChild' => false,
'hideEmptyPreview' => null,
'showProceedLink' => null,
'printDetails' => false ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => false,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'ArticleID' => array( 'totalsType' => '' ),
'ArticleID2' => array( 'totalsType' => '' ),
'ArticleIDedit' => array( 'totalsType' => '' ),
'Category' => array( 'totalsType' => '' ),
'DateCreated' => array( 'totalsType' => '' ),
'Problem' => array( 'totalsType' => '' ),
'Solution' => array( 'totalsType' => '' ),
'Title' => array( 'totalsType' => '' ),
'Views' => array( 'totalsType' => '' ),
'helpfullblock' => array( 'totalsType' => '' ),
'likecount' => array( 'totalsType' => '' ),
'dislikecount' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Title',
'Problem',
'Views' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'Title' => array( 'simple_grid_field6' ),
'Problem' => array( 'grid_field' ),
'Views' => array( 'grid_field1' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'snippet1',
'simple_search',
'snippet',
'text',
'text2',
'text1' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'menu',
'logo',
'expand_button' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'list_options',
'notifications',
'loginform_login',
'username_button' ),
'grid' => array( 'simple_grid_field6',
'category_title',
'grid_field',
'grid_field1' ),
'top' => array(  ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'snippet1' => 'above-grid',
'simple_search' => 'above-grid',
'snippet' => 'above-grid',
'text' => 'above-grid',
'text2' => 'above-grid',
'text1' => 'above-grid',
'pagination' => 'below-grid',
'menu' => 'left',
'logo' => 'left',
'expand_button' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'list_options' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'simple_grid_field6' => 'grid',
'category_title' => 'grid',
'grid_field' => 'grid',
'grid_field1' => 'grid' ),
'itemLocations' => array( 'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'category_title' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'snippet' => array( 'category_title',
'snippet',
'snippet1' ),
'pagination' => array( 'pagination' ),
'grid_field' => array( 'simple_grid_field6',
'grid_field',
'grid_field1' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'export_selected' => array( 'export_selected' ),
'-' => array( '-1',
'-',
'-2',
'-3' ),
'advsearch_link' => array( 'advsearch_link' ),
'export' => array( 'export' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'list_options' => array( 'list_options' ),
'loginform_login' => array( 'loginform_login' ),
'username_button' => array( 'username_button' ),
'logo' => array( 'logo' ),
'text' => array( 'text',
'text1',
'text2' ),
'breadcrumb' => array( 'breadcrumb' ),
'notifications' => array( 'notifications' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'Title_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'category_title' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'Problem_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'Views_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 5 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 1,
'recsPerRow' => 4,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'category',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 1,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'snippet1' ),
'align' => 'center' ),
'c3' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'snippet' ),
'align' => 'center' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'text' ),
'align' => 'center',
'color' => '#0075d9',
'background' => '#e7fdfe',
'underline' => true,
'bold' => true ),
'c4' => array( 'model' => 'c3',
'items' => array( 'text2' ),
'pageBreak' => 'before',
'align' => 'center' ),
'c7' => array( 'model' => 'c1',
'items' => array( 'text1' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ),
'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'list_options',
'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'vertical-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 1 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_field',
'colspan' => 1 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_field1',
'colspan' => 1 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_field2',
'colspan' => 1 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 1 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array( 'simple_grid_field6' ),
'align' => 'center',
'field' => 'Title',
'columnName' => 'field' ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'category_title' ) ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'align' => 'center',
'field' => 'Problem',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'align' => 'right',
'field' => 'Views',
'columnName' => 'field' ) ),
'deferredItems' => array( 'grid_checkbox_head' ),
'recsPerRow' => 4 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'category_title' => array( 'eventId' => 'category_title',
'label' => array( 'text' => 'category_title',
'type' => 0 ),
'type' => 'snippet',
'customCSS' => '/* Put  your custom CSS code here */

:host {
    font-family: "Montserrat",sans-serif;
    color: #1b1b1b;
        font-size: 20px;
}
',
'bold' => true,
'italic' => true ),
'pagination' => array( 'type' => 'pagination' ),
'simple_grid_field6' => array( 'field' => 'Title',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'customCSS' => '/* Put  your custom CSS code here */

:host a {
  font-size: 18px;
}
:host a:before{
    margin-right:5px;
}
',
'bold' => true,
'color' => '#0097d3',
'font-size' => '19px' ),
'grid_field' => array( 'field' => 'Problem',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field1' => array( 'field' => 'Views',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-' => array( 'type' => '-' ),
'export' => array( 'type' => 'export' ),
'-2' => array( 'type' => '-' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'-1',
'advsearch_link',
'-',
'export' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link' ) ),
'logo' => array( 'type' => 'logo' ),
'text' => array( 'type' => 'text',
'label' => array( 'label' => 'HOW_CAN_WE_HELP_YOU_',
'table' => null,
'type' => 1 ),
'editedByRte' => false,
'customCSS' => ':host {
    font-size: 34px;
    line-height: 40px;
    font-weight: 600;
    color: #ffffff;
    margin-top: 40px;
    margin-bottom: 40px;
}
',
'mobileDisplay' => 'both',
'bold' => false,
'color' => '#0075d9',
'mobileControl' => 'always',
'background' => '#0075d9' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'snippet' => array( 'eventId' => 'category_select',
'label' => array( 'text' => 'category_select',
'type' => 0 ),
'type' => 'snippet' ),
'-3' => array( 'type' => '-' ),
'notifications' => array( 'type' => 'notifications' ),
'text1' => array( 'type' => 'text',
'label' => array( 'label' => '_BR__',
'table' => null,
'type' => 1 ),
'editedByRte' => false,
'color' => '#00293c',
'bold' => true,
'font-size' => '21px' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'snippet1' => array( 'type' => 'snippet',
'eventId' => 'catefory_list',
'label' => array( 'text' => 'category_list',
'type' => 0 ),
'pageBreak' => 'after',
'color' => '#0079d3',
'bold' => true ),
'text2' => array( 'type' => 'text',
'label' => array( 'type' => 1,
'label' => 'MOST_VISITED_CONTENTS' ),
'editedByRte' => false,
'italic' => true,
'bold' => true ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 11,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>