<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'MFR_Region_Region',
'MFR_Zone_Zone',
'MFR_Woreda_Woreda' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'MFR_Region_Region' => array( 'integrated_search_field' ),
'MFR_Zone_Zone' => array( 'integrated_search_field1' ),
'MFR_Woreda_Woreda' => array( 'integrated_search_field2' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'top' => array( 'search_header' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'search_header' => 'top',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashSearch' => array( 'searchFields' => array( 'MFR_Region_Region' => array( array( 'field' => 'Region',
'table' => 'MFR_Region' ) ),
'MFR_Region_Lat' => array( array( 'field' => 'Lat',
'table' => 'MFR_Region' ) ),
'MFR_Region_Lng' => array( array( 'field' => 'Lng',
'table' => 'MFR_Region' ) ),
'MFR_Region_Count' => array( array( 'field' => 'Count',
'table' => 'MFR_Region' ) ),
'MFR_Zone_Zone' => array( array( 'field' => 'Zone',
'table' => 'MFR_Zone' ) ),
'MFR_Zone_Lat' => array( array( 'field' => 'Lat',
'table' => 'MFR_Zone' ) ),
'MFR_Zone_Lng' => array( array( 'field' => 'Lng',
'table' => 'MFR_Zone' ) ),
'MFR_Zone_Count' => array( array( 'field' => 'Count',
'table' => 'MFR_Zone' ) ),
'MFR_Woreda_Woreda' => array( array( 'field' => 'Woreda',
'table' => 'MFR_Woreda' ) ),
'MFR_Woreda_Lat' => array( array( 'field' => 'Lat',
'table' => 'MFR_Woreda' ) ),
'MFR_Woreda_Lng' => array( array( 'field' => 'Lng',
'table' => 'MFR_Woreda' ) ),
'MFR_Woreda_Count' => array( array( 'field' => 'Count',
'table' => 'MFR_Woreda' ) ) ),
'allSearchFields' => array( 'MFR_Region_Region',
'MFR_Region_Lat',
'MFR_Region_Lng',
'MFR_Region_Count',
'MFR_Zone_Zone',
'MFR_Zone_Lat',
'MFR_Zone_Lng',
'MFR_Zone_Count',
'MFR_Woreda_Woreda',
'MFR_Woreda_Lat',
'MFR_Woreda_Lng',
'MFR_Woreda_Count' ),
'googleLikeFields' => array( 'MFR_Region_Region',
'MFR_Zone_Zone',
'MFR_Woreda_Woreda' ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2' ) ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'MFR_Region_Region',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field1' => array( 'field' => 'MFR_Zone_Zone',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field2' => array( 'field' => 'MFR_Woreda_Woreda',
'type' => 'integrated_search_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>