<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'dashboard-item1',
'dashboard-item2',
'text',
'text1',
'dashboard-item5',
'dashboard-item',
'dashboard-item4',
'dashboard-item3' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'notifications',
'username_button' ),
'top' => array(  ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'dashboard-item1' => 'grid',
'dashboard-item2' => 'grid',
'text' => 'grid',
'text1' => 'grid',
'dashboard-item5' => 'grid',
'dashboard-item' => 'grid',
'dashboard-item4' => 'grid',
'dashboard-item3' => 'grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'notifications' => 'supertop',
'username_button' => 'supertop' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'text' => array( 'text',
'text1' ),
'dashboard-item' => array( 'dashboard-item',
'dashboard-item1',
'dashboard-item2',
'dashboard-item3',
'dashboard-item4',
'dashboard-item5' ),
'notifications' => array( 'notifications' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic',
'dashType' => 0,
'dashName' => 'public_ethprism_national_prism_woreda_level_diagnostic_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'camera' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'elementName' => 'public_ethprism_national_prism_woreda_level_diagnostic_grid',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic',
'dashType' => 0,
'dashName' => 'public_ethprism_facility_level_rhis_performance_diagnostic_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'shopping-cart' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'elementName' => 'public_ethprism_facility_level_rhis_performance_diagnostic_grid',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic',
'dashType' => 0,
'dashName' => 'public_ethprism_healthpost_level_rhis_performance_diagnostic_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'bell' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'elementName' => 'public_ethprism_healthpost_level_rhis_performance_diagnostic_grid',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'public.ethprism_facility_office_checklist',
'dashType' => 0,
'dashName' => 'public_ethprism_facility_office_checklist_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'gift' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'elementName' => 'public_ethprism_facility_office_checklist_grid',
'table' => 'public.ethprism_facility_office_checklist',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'public.ethprism_organizational_and_behavioral_assessment',
'dashType' => 0,
'dashName' => 'public_ethprism_organizational_and_behavioral_assessment_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'send' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'elementName' => 'public_ethprism_organizational_and_behavioral_assessment_grid',
'table' => 'public.ethprism_organizational_and_behavioral_assessment',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment',
'dashType' => 0,
'dashName' => 'public_ethprism_additional_organizational_and_behavioral_assessment_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'barcode' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'elementName' => 'public_ethprism_additional_organizational_and_behavioral_assessment_grid',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'public_ethprism_additional_organizational_and_behavioral_assessment_CompletionDate' => array( array( 'field' => 'CompletionDate',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_SubmissionDate' => array( array( 'field' => 'SubmissionDate',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_starttime' => array( array( 'field' => 'starttime',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_endtime' => array( array( 'field' => 'endtime',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_deviceid' => array( array( 'field' => 'deviceid',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_subscriberid' => array( array( 'field' => 'subscriberid',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_simid' => array( array( 'field' => 'simid',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_devicephonenum' => array( array( 'field' => 'devicephonenum',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_username' => array( array( 'field' => 'username',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_duration' => array( array( 'field' => 'duration',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_caseid' => array( array( 'field' => 'caseid',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT101' => array( array( 'field' => 'OBAT101',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT102' => array( array( 'field' => 'OBAT102',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT103' => array( array( 'field' => 'OBAT103',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT104' => array( array( 'field' => 'OBAT104',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_admin_lvl' => array( array( 'field' => 'admin_lvl',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT105' => array( array( 'field' => 'OBAT105',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT106' => array( array( 'field' => 'OBAT106',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT107' => array( array( 'field' => 'OBAT107',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT108' => array( array( 'field' => 'OBAT108',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_siteid' => array( array( 'field' => 'siteid',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT109f' => array( array( 'field' => 'OBAT109f',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT110f' => array( array( 'field' => 'OBAT110f',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT111' => array( array( 'field' => 'OBAT111',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT112' => array( array( 'field' => 'OBAT112',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD1' => array( array( 'field' => 'DD1',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD2' => array( array( 'field' => 'DD2',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD3a' => array( array( 'field' => 'DD3a',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD3b' => array( array( 'field' => 'DD3b',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD4a' => array( array( 'field' => 'DD4a',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD4b' => array( array( 'field' => 'DD4b',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5a' => array( array( 'field' => 'DD5a',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5b' => array( array( 'field' => 'DD5b',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_1' => array( array( 'field' => 'DD5c_1',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_2' => array( array( 'field' => 'DD5c_2',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_3' => array( array( 'field' => 'DD5c_3',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_5' => array( array( 'field' => 'DD5c_5',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_96' => array( array( 'field' => 'DD5c_96',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5co' => array( array( 'field' => 'DD5co',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_SubmissionDate' => array( array( 'field' => 'SubmissionDate',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_starttime' => array( array( 'field' => 'starttime',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_endtime' => array( array( 'field' => 'endtime',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_deviceid' => array( array( 'field' => 'deviceid',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_subscriberid' => array( array( 'field' => 'subscriberid',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_simid' => array( array( 'field' => 'simid',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_devicephonenum' => array( array( 'field' => 'devicephonenum',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_username' => array( array( 'field' => 'username',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_duration' => array( array( 'field' => 'duration',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_caseid' => array( array( 'field' => 'caseid',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_DQ104' => array( array( 'field' => 'DQ104',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ101' => array( array( 'field' => 'intvwr_vst_DQ101',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ102' => array( array( 'field' => 'intvwr_vst_DQ102',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ102_Other' => array( array( 'field' => 'intvwr_vst_DQ102_Other',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ105' => array( array( 'field' => 'distr_unit_id_DQ105',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ106' => array( array( 'field' => 'distr_unit_id_DQ106',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ106_Other' => array( array( 'field' => 'distr_unit_id_DQ106_Other',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ108' => array( array( 'field' => 'distr_unit_id_DQ108',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_siteid' => array( array( 'field' => 'siteid',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_national_prism_woreda_level_diagnostic_gen_info_DQ109' => array( array( 'field' => 'gen_info_DQ109',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_CompletionDate' => array( array( 'field' => 'CompletionDate',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_SubmissionDate' => array( array( 'field' => 'SubmissionDate',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_starttime' => array( array( 'field' => 'starttime',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_endtime' => array( array( 'field' => 'endtime',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_deviceid' => array( array( 'field' => 'deviceid',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_subscriberid' => array( array( 'field' => 'subscriberid',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_simid' => array( array( 'field' => 'simid',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_devicephonenum' => array( array( 'field' => 'devicephonenum',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_username' => array( array( 'field' => 'username',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_duration' => array( array( 'field' => 'duration',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_caseid' => array( array( 'field' => 'caseid',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ104' => array( array( 'field' => 'FQ104',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ101' => array( array( 'field' => 'FQ101',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ102' => array( array( 'field' => 'FQ102',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ103' => array( array( 'field' => 'FQ103',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ105' => array( array( 'field' => 'FQ105',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ106' => array( array( 'field' => 'FQ106',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ107' => array( array( 'field' => 'FQ107',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ108' => array( array( 'field' => 'FQ108',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_siteid' => array( array( 'field' => 'siteid',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ109' => array( array( 'field' => 'FQ109',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ110' => array( array( 'field' => 'FQ110',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ111' => array( array( 'field' => 'FQ111',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ112' => array( array( 'field' => 'FQ112',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ113' => array( array( 'field' => 'FQ113',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic' ) ),
'public_ethprism_facility_office_checklist_CompletionDate' => array( array( 'field' => 'CompletionDate',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_SubmissionDate' => array( array( 'field' => 'SubmissionDate',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_starttime' => array( array( 'field' => 'starttime',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_endtime' => array( array( 'field' => 'endtime',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_deviceid' => array( array( 'field' => 'deviceid',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_subscriberid' => array( array( 'field' => 'subscriberid',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_simid' => array( array( 'field' => 'simid',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_devicephonenum' => array( array( 'field' => 'devicephonenum',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_username' => array( array( 'field' => 'username',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_duration' => array( array( 'field' => 'duration',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_caseid' => array( array( 'field' => 'caseid',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_FOC105' => array( array( 'field' => 'FOC105',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_FOC101' => array( array( 'field' => 'FOC101',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_FOC102' => array( array( 'field' => 'FOC102',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_FOC103' => array( array( 'field' => 'FOC103',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_FOC104' => array( array( 'field' => 'FOC104',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_admin_lvl' => array( array( 'field' => 'admin_lvl',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_admin_lvl2' => array( array( 'field' => 'admin_lvl2',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_FOC106' => array( array( 'field' => 'FOC106',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_FOC107' => array( array( 'field' => 'FOC107',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_FOC108' => array( array( 'field' => 'FOC108',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_siteid' => array( array( 'field' => 'siteid',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_FOC109f' => array( array( 'field' => 'FOC109f',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_FOC110f' => array( array( 'field' => 'FOC110f',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_facility_office_checklist_FOC111' => array( array( 'field' => 'FOC111',
'table' => 'public.ethprism_facility_office_checklist' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_CompletionDate' => array( array( 'field' => 'CompletionDate',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_SubmissionDate' => array( array( 'field' => 'SubmissionDate',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_starttime' => array( array( 'field' => 'starttime',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_endtime' => array( array( 'field' => 'endtime',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_deviceid' => array( array( 'field' => 'deviceid',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_subscriberid' => array( array( 'field' => 'subscriberid',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_simid' => array( array( 'field' => 'simid',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_devicephonenum' => array( array( 'field' => 'devicephonenum',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_username' => array( array( 'field' => 'username',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_duration' => array( array( 'field' => 'duration',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_caseid' => array( array( 'field' => 'caseid',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ104' => array( array( 'field' => 'HPQ104',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ101' => array( array( 'field' => 'HPQ101',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ102' => array( array( 'field' => 'HPQ102',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ105' => array( array( 'field' => 'HPQ105',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ106' => array( array( 'field' => 'HPQ106',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ106_Other' => array( array( 'field' => 'HPQ106_Other',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ107' => array( array( 'field' => 'HPQ107',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ108' => array( array( 'field' => 'HPQ108',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_siteid' => array( array( 'field' => 'siteid',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ109' => array( array( 'field' => 'HPQ109',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ110' => array( array( 'field' => 'HPQ110',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic' ) ),
'public_ethprism_organizational_and_behavioral_assessment_CompletionDate' => array( array( 'field' => 'CompletionDate',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_SubmissionDate' => array( array( 'field' => 'SubmissionDate',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_starttime' => array( array( 'field' => 'starttime',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_endtime' => array( array( 'field' => 'endtime',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_deviceid' => array( array( 'field' => 'deviceid',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_subscriberid' => array( array( 'field' => 'subscriberid',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_simid' => array( array( 'field' => 'simid',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_devicephonenum' => array( array( 'field' => 'devicephonenum',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_username' => array( array( 'field' => 'username',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_duration' => array( array( 'field' => 'duration',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_caseid' => array( array( 'field' => 'caseid',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_OBAT101' => array( array( 'field' => 'OBAT101',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_OBAT102' => array( array( 'field' => 'OBAT102',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_OBAT104' => array( array( 'field' => 'OBAT104',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_admin_lvl' => array( array( 'field' => 'admin_lvl',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_OBAT105' => array( array( 'field' => 'OBAT105',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_OBAT106' => array( array( 'field' => 'OBAT106',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_OBAT107' => array( array( 'field' => 'OBAT107',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_OBAT108' => array( array( 'field' => 'OBAT108',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_siteid' => array( array( 'field' => 'siteid',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_OBAT109f' => array( array( 'field' => 'OBAT109f',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_OBAT110f' => array( array( 'field' => 'OBAT110f',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_OBAT111' => array( array( 'field' => 'OBAT111',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ),
'public_ethprism_organizational_and_behavioral_assessment_OBAT112' => array( array( 'field' => 'OBAT112',
'table' => 'public.ethprism_organizational_and_behavioral_assessment' ) ) ),
'allSearchFields' => array( 'public_ethprism_additional_organizational_and_behavioral_assessment_CompletionDate',
'public_ethprism_additional_organizational_and_behavioral_assessment_SubmissionDate',
'public_ethprism_additional_organizational_and_behavioral_assessment_starttime',
'public_ethprism_additional_organizational_and_behavioral_assessment_endtime',
'public_ethprism_additional_organizational_and_behavioral_assessment_deviceid',
'public_ethprism_additional_organizational_and_behavioral_assessment_subscriberid',
'public_ethprism_additional_organizational_and_behavioral_assessment_simid',
'public_ethprism_additional_organizational_and_behavioral_assessment_devicephonenum',
'public_ethprism_additional_organizational_and_behavioral_assessment_username',
'public_ethprism_additional_organizational_and_behavioral_assessment_duration',
'public_ethprism_additional_organizational_and_behavioral_assessment_caseid',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT101',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT102',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT103',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT104',
'public_ethprism_additional_organizational_and_behavioral_assessment_admin_lvl',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT105',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT106',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT107',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT108',
'public_ethprism_additional_organizational_and_behavioral_assessment_siteid',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT109f',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT110f',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT111',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT112',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD1',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD2',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD3a',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD3b',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD4a',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD4b',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5a',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5b',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_1',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_2',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_3',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_5',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_96',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5co',
'public_ethprism_national_prism_woreda_level_diagnostic_SubmissionDate',
'public_ethprism_national_prism_woreda_level_diagnostic_starttime',
'public_ethprism_national_prism_woreda_level_diagnostic_endtime',
'public_ethprism_national_prism_woreda_level_diagnostic_deviceid',
'public_ethprism_national_prism_woreda_level_diagnostic_subscriberid',
'public_ethprism_national_prism_woreda_level_diagnostic_simid',
'public_ethprism_national_prism_woreda_level_diagnostic_devicephonenum',
'public_ethprism_national_prism_woreda_level_diagnostic_username',
'public_ethprism_national_prism_woreda_level_diagnostic_duration',
'public_ethprism_national_prism_woreda_level_diagnostic_caseid',
'public_ethprism_national_prism_woreda_level_diagnostic_DQ104',
'public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ101',
'public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ102',
'public_ethprism_national_prism_woreda_level_diagnostic_intvwr_vst_DQ102_Other',
'public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ105',
'public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ106',
'public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ106_Other',
'public_ethprism_national_prism_woreda_level_diagnostic_distr_unit_id_DQ108',
'public_ethprism_national_prism_woreda_level_diagnostic_siteid',
'public_ethprism_national_prism_woreda_level_diagnostic_gen_info_DQ109',
'public_ethprism_facility_level_rhis_performance_diagnostic_CompletionDate',
'public_ethprism_facility_level_rhis_performance_diagnostic_SubmissionDate',
'public_ethprism_facility_level_rhis_performance_diagnostic_starttime',
'public_ethprism_facility_level_rhis_performance_diagnostic_endtime',
'public_ethprism_facility_level_rhis_performance_diagnostic_deviceid',
'public_ethprism_facility_level_rhis_performance_diagnostic_subscriberid',
'public_ethprism_facility_level_rhis_performance_diagnostic_simid',
'public_ethprism_facility_level_rhis_performance_diagnostic_devicephonenum',
'public_ethprism_facility_level_rhis_performance_diagnostic_username',
'public_ethprism_facility_level_rhis_performance_diagnostic_duration',
'public_ethprism_facility_level_rhis_performance_diagnostic_caseid',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ104',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ101',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ102',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ103',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ105',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ106',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ107',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ108',
'public_ethprism_facility_level_rhis_performance_diagnostic_siteid',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ109',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ110',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ111',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ112',
'public_ethprism_facility_level_rhis_performance_diagnostic_FQ113',
'public_ethprism_facility_office_checklist_CompletionDate',
'public_ethprism_facility_office_checklist_SubmissionDate',
'public_ethprism_facility_office_checklist_starttime',
'public_ethprism_facility_office_checklist_endtime',
'public_ethprism_facility_office_checklist_deviceid',
'public_ethprism_facility_office_checklist_subscriberid',
'public_ethprism_facility_office_checklist_simid',
'public_ethprism_facility_office_checklist_devicephonenum',
'public_ethprism_facility_office_checklist_username',
'public_ethprism_facility_office_checklist_duration',
'public_ethprism_facility_office_checklist_caseid',
'public_ethprism_facility_office_checklist_FOC105',
'public_ethprism_facility_office_checklist_FOC101',
'public_ethprism_facility_office_checklist_FOC102',
'public_ethprism_facility_office_checklist_FOC103',
'public_ethprism_facility_office_checklist_FOC104',
'public_ethprism_facility_office_checklist_admin_lvl',
'public_ethprism_facility_office_checklist_admin_lvl2',
'public_ethprism_facility_office_checklist_FOC106',
'public_ethprism_facility_office_checklist_FOC107',
'public_ethprism_facility_office_checklist_FOC108',
'public_ethprism_facility_office_checklist_siteid',
'public_ethprism_facility_office_checklist_FOC109f',
'public_ethprism_facility_office_checklist_FOC110f',
'public_ethprism_facility_office_checklist_FOC111',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_CompletionDate',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_SubmissionDate',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_starttime',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_endtime',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_deviceid',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_subscriberid',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_simid',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_devicephonenum',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_username',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_duration',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_caseid',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ104',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ101',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ102',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ105',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ106',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ106_Other',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ107',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ108',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_siteid',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ109',
'public_ethprism_healthpost_level_rhis_performance_diagnostic_HPQ110',
'public_ethprism_organizational_and_behavioral_assessment_CompletionDate',
'public_ethprism_organizational_and_behavioral_assessment_SubmissionDate',
'public_ethprism_organizational_and_behavioral_assessment_starttime',
'public_ethprism_organizational_and_behavioral_assessment_endtime',
'public_ethprism_organizational_and_behavioral_assessment_deviceid',
'public_ethprism_organizational_and_behavioral_assessment_subscriberid',
'public_ethprism_organizational_and_behavioral_assessment_simid',
'public_ethprism_organizational_and_behavioral_assessment_devicephonenum',
'public_ethprism_organizational_and_behavioral_assessment_username',
'public_ethprism_organizational_and_behavioral_assessment_duration',
'public_ethprism_organizational_and_behavioral_assessment_caseid',
'public_ethprism_organizational_and_behavioral_assessment_OBAT101',
'public_ethprism_organizational_and_behavioral_assessment_OBAT102',
'public_ethprism_organizational_and_behavioral_assessment_OBAT104',
'public_ethprism_organizational_and_behavioral_assessment_admin_lvl',
'public_ethprism_organizational_and_behavioral_assessment_OBAT105',
'public_ethprism_organizational_and_behavioral_assessment_OBAT106',
'public_ethprism_organizational_and_behavioral_assessment_OBAT107',
'public_ethprism_organizational_and_behavioral_assessment_OBAT108',
'public_ethprism_organizational_and_behavioral_assessment_siteid',
'public_ethprism_organizational_and_behavioral_assessment_OBAT109f',
'public_ethprism_organizational_and_behavioral_assessment_OBAT110f',
'public_ethprism_organizational_and_behavioral_assessment_OBAT111',
'public_ethprism_organizational_and_behavioral_assessment_OBAT112' ),
'googleLikeFields' => array( 'public_ethprism_additional_organizational_and_behavioral_assessment_CompletionDate',
'public_ethprism_additional_organizational_and_behavioral_assessment_SubmissionDate',
'public_ethprism_additional_organizational_and_behavioral_assessment_starttime',
'public_ethprism_additional_organizational_and_behavioral_assessment_endtime',
'public_ethprism_additional_organizational_and_behavioral_assessment_deviceid',
'public_ethprism_additional_organizational_and_behavioral_assessment_subscriberid',
'public_ethprism_additional_organizational_and_behavioral_assessment_simid',
'public_ethprism_additional_organizational_and_behavioral_assessment_devicephonenum',
'public_ethprism_additional_organizational_and_behavioral_assessment_username',
'public_ethprism_additional_organizational_and_behavioral_assessment_duration',
'public_ethprism_additional_organizational_and_behavioral_assessment_caseid',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT101',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT102',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT103',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT104',
'public_ethprism_additional_organizational_and_behavioral_assessment_admin_lvl',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT105',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT106',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT107',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT108',
'public_ethprism_additional_organizational_and_behavioral_assessment_siteid',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT109f',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT110f',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT111',
'public_ethprism_additional_organizational_and_behavioral_assessment_OBAT112',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD1',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD2',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD3a',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD3b',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD4a',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD4b',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5a',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5b',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_1',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_2',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_3',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_5',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5c_96',
'public_ethprism_additional_organizational_and_behavioral_assessment_DD5co' ) ) );
			$pageArray = array( 'id' => 'PRISM_Dashboard',
'type' => 'dashboard',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 1,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'dashboard-item1' ),
'width' => '100%' ),
'c' => array( 'model' => 'c1',
'items' => array( 'dashboard-item2' ),
'width' => '100%' ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'text' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'text1' ) ),
'c6' => array( 'model' => 'c1',
'items' => array(  ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array(  ) ),
'c9' => array( 'model' => 'c1',
'items' => array(  ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'dashboard-item5' ),
'width' => '100%' ),
'c11' => array( 'model' => 'c1',
'items' => array( 'dashboard-item' ),
'width' => '100%' ),
'c12' => array( 'model' => 'c1',
'items' => array( 'dashboard-item4' ),
'width' => '100%' ),
'c13' => array( 'model' => 'c1',
'items' => array( 'dashboard-item3' ),
'width' => '100%' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'notifications',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<b>PRISM ASSESSMENT<b>
<br>
<br>',
'type' => 0 ),
'editedByRte' => false ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => '<b>DASHBOARD<b>
<br>
<br>',
'type' => 0 ),
'editedByRte' => false ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'public.ethprism_additional_organizational_and_behavioral_assessment',
'dashType' => 0,
'dashName' => 'public_ethprism_additional_organizational_and_behavioral_assessment_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'barcode' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'dashboard-item1' => array( 'type' => 'dashboard-item',
'table' => 'public.ethprism_national_prism_woreda_level_diagnostic',
'dashType' => 0,
'dashName' => 'public_ethprism_national_prism_woreda_level_diagnostic_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'camera' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'dashboard-item2' => array( 'type' => 'dashboard-item',
'table' => 'public.ethprism_facility_level_rhis_performance_diagnostic',
'dashType' => 0,
'dashName' => 'public_ethprism_facility_level_rhis_performance_diagnostic_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'shopping-cart' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'dashboard-item3' => array( 'type' => 'dashboard-item',
'table' => 'public.ethprism_facility_office_checklist',
'dashType' => 0,
'dashName' => 'public_ethprism_facility_office_checklist_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'gift' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'dashboard-item4' => array( 'type' => 'dashboard-item',
'table' => 'public.ethprism_healthpost_level_rhis_performance_diagnostic',
'dashType' => 0,
'dashName' => 'public_ethprism_healthpost_level_rhis_performance_diagnostic_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'bell' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'dashboard-item5' => array( 'type' => 'dashboard-item',
'table' => 'public.ethprism_organizational_and_behavioral_assessment',
'dashType' => 0,
'dashName' => 'public_ethprism_organizational_and_behavioral_assessment_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'send' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list' ),
'notifications' => array( 'type' => 'notifications' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>